### ISSUE TITLE
Steam VR 1.2.1 not detected

### ISSUE THREAD

**Issue by jhurlbut** [thestonefox/VRTK#1018]
### Environment

 * github
 * 619736a990ea620c85fccae65cd80c49e4e188e4
 * 5.5.0f3 64bit

### Steps to reproduce

upgrade SteamVR to 1.2.1. click VRTK. Will now say SteamVR SDK is not installed.

### Expected behavior

SteamVR SDK should be marked as installed

### Current behavior

Can no longer use SteamVR with VRTK

**Comment by thestonefox** [comment]
I'm using SteamVR 1.2.1 with VRTK, I think most people are.

Perhaps there is another issue with your setup?

**Comment by quintesse** [comment]
@jhurlbut I'm not sure if you're using a previously existing project that you updated but had something similar and in the end I resorted to deleting all the non-essential files like "Library" and the .slns and .csproj etc. And that seemed to fix it. You might try if it fixes your problem as well. Who knows,

**Comment by bddckr** [comment]
Some also had the issue with the Asset Store basically breaking their cached SteamVR plugin copy. Try deleting that cached one and redownload the plugin from the Asset Store again and reimport that after removing the SteamVR folder from your project.

This worked for multiple people now.

**Comment by jhurlbut** [comment]
Deleting the cached copy of SteamVR fixed it. thanks

**Comment by ZnelArts** [comment]
Im still observing this issue in 3,1,0

**Comment by ZnelArts** [comment]
The issue is still observed in the latest Github version, there are no errors in the project since Steam VR and VRTK version previous dynamic SDK discovery are working fine until I upgrade VRTK.

None of the suggested fixes are working, with the latest VRTK version I get the following error:

Ignoring SDK Setup 'SteamVR' because there are some errors with it:

The vendor SDK for 'SteamVR' is not installed.

**Comment by thestonefox** [comment]
The issue is not present for everyone.

Look at this latest video for setting up with steamvr

https://www.youtube.com/watch?v=tyFV9oBReqg

I literally go through the set up from downloading from GitHub and I do not get any errors.

So whatever error you're getting is probably limited to your situation.

**Comment by bddckr** [comment]
@ZnelArts I suggest to join the [VRTK Slack](http://invite.vrtk.io/) so it's easier to figure out where your config differs.

**Comment by ZnelArts** [comment]
The issue is reproducible with the steps provided.

I have tracked the issue to the exact commit where it fails, a project will break when updating VRTK to https://github.com/thestonefox/VRTK/commit/eb96658992c870aa0ae5c9beec63ecb3f6f6296c

Previous that commit SteamVR is detected as installed, after upgrading it will not detect it as installed.

**Comment by ZnelArts** [comment]
By reverting this commit https://github.com/thestonefox/VRTK/commit/eb96658992c870aa0ae5c9beec63ecb3f6f6296c

On the current master and updating the project then VRTK is able to detect SteamVR as installed.

Could it be that reflection may not be working well by some reason and the script is relying on reflection to detect a symbol from SteamVR? Could it be that the order the editor pre compiles symbols can be causing this issue and the EVREventType is not ready at the time the script runs. This is weird because by using its type wont throw errors.

I wouldnt close this issue yet without a clear root cause of the problem.

**Comment by frank-alonso** [comment]
@ZnelArts thanks for following up on this topic, it helped me find a temporary solution to the issue.

I upgraded VRTK to the current master to fix an issue with the UI, but then encountered the same issue with SteamVR not being detected and the Oculus Library being defaulted even though it was not downloaded. When I tried to adjust Scripting Define Symbols in Player Settings to erase all mentions of VRTK, it would repopulate with VRTK Oculus SDK after recompile.  I also tried redownloading and reimporting SteamVR and VRTK as well as deleting the Library folder of my project. 

The only thing that addressed the issue was reverting before the commit you mentioned [eb96658](https://github.com/thestonefox/VRTK/commit/eb96658992c870aa0ae5c9beec63ecb3f6f6296c).
