### ISSUE TITLE
Snap zones change grab mode in certain circumstances

### ISSUE THREAD

**Issue by quintesse** [thestonefox/VRTK#1056]
### Environment

 * GitHub master
 * 8bdf9d0db7b1e4def83494964013d5dfe4764548
 * Version of Unity3D (e.g. Unity 5.5.1f1)

### Steps to reproduce

Go to example 041 "Controller_ObjectSnappingToDropZones". Grab the green sphere with one controller and the red one with the other. Hold them both in the snap zone. Now let the red one go. Now pick up the green one again.

### Expected behavior

The green one should still be using the grab toggle mode (click once to grab, click again to release),

### Current behavior

The green sphere has a toggle grab mechanism. If you enter both spheres into the drop zone and let go of the red sphere, the green sphere will drop but it will also have lost its toggle state and have become "hold to grip"!

Edit: Before the issue states actually two problems. Of which one wasn't correct. So I edited it to leave only the second problem. Sorry about that.

**Comment by thestonefox** [comment]
Not sure I understand the issue here.

In the example scene, the green sphere isn't set to `Hold Button To Grab = false` and it's also set to have a `Valid Drop = Drop Valid Snap Drop Zone`

This means the green sphere can only be dropped in a snap drop zone so by default you can never release the green sphere anyway unless you're doing it in a snap drop zone.

However, I've also tried changing the green sphere to `Drop Anywhere` and unticking the `Hold Button To Grab` but even then I don't see the behaviour you're reporting where the toggle state is changed.

The only thing I do notice (which I'd say is a bug) is that when you drop the red sphere you also automatically drop the green sphere even though you've not released the button. I'm guessing this is because the snap drop zone is calling force release on the touching object even though it's not the valid object to release.

**Comment by quintesse** [comment]
> The only thing I do notice (which I'd say is a bug) is that when you drop the red sphere you also automatically drop the green sphere even though you've not released the button.

Well I thought at first that was a bug too but it's just because the drop of the first object gives it such a push that its joint "breaks". So that seems correct (although not necessarily desired or expected) behaviour, right?

> This means the green sphere can only be dropped in a snap drop zone so by default you can never release the green sphere anyway unless you're doing it in a snap drop zone.

Ok, then I explained it wrong. Seeing the behaviour I assumed the "Hold Button To Grab" had to be false because I was obviously not holding the grip button pressed. But it seems there's an "implicit" hold to grab when you use "Drop Valid Snap Drop Zone", okay.

Anyway the bug is that when you put both spheres in the snap drop zone and let go of the red one so it snaps it will push the green one breaking its joint so it falls.

Now try picking up the green one again. You can now simply let it drop again even though "Drop Valid Snap Drop Zone" is supposedly set.

.... except that after having reproduced this several times yesterday I can't do so now anymore. No idea what was happening yesterday or what I'm doing different this time. But closing until such time I can reproduce again (if ever). Sorry for the noise.
