### ISSUE TITLE
Walk In Place & body physics allows player to pass between the join of two box colliders

### ISSUE THREAD

**Issue by roskelld** [thestonefox/VRTK#1111]
### Environment

 * Source of VRTK (Github)
 * Version of VRTK (3.1.0)
 * Version of Unity3D (Unity 5.6.0F3)
 * Hardware used (Vive)
 * SDK used (OpenVR)

### Steps to reproduce

Load 042_CaneraRig_MoveInPlace
Change the VRTK_MoveInPlace parameters:
- Speed Scale = 3
- Max Speed = 15

Run level
Using Move In Place head to the corner of the red walls where the two walls intersect.
Perform a quick move in place motion.
The avatar will pop through the collision

### Expected behavior

Expected to hit the collision and stop moving

### Current behavior

Avatar is colliding with the collision intersect which is being resolved by popping it through. If you test this against the middle of a wall where there's no intersect you will not go through the wall, even if you increase the max speed and speed scale to much higher numbers.

**Comment by thestonefox** [comment]
I'm guessing this is a unity glitch where rigidbodies are just conflicting when the collision resolution is done.

I'll take a further look though.

**Comment by thestonefox** [comment]
Looks like a Unity collision tunnelling issue because the play area is having it's position forcibly set

**Comment by thestonefox** [comment]
I've looked into this and it is a Unity collision tunnelling issue.

It's because the play area is being moved with the `transform.position` and therefore unity is struggling to resolve the rigidbody collisions where colliders intersect.

The short term work around would be to overlap your colliders so there is no hard line between them then unity has an easier time resolving collisions.

A longer term solution would be to potentially move the play area around based on rigidbody velocities as then this should be considered in collision resolutions in the unity physics steps.
