### ISSUE TITLE
Add OVRAvatar hand model population to VRTK_SDKManager

### ISSUE THREAD

**Issue by BinaryLegend** [thestonefox/VRTK#1140]
Currently the VRTK_SDKManager populates with the Controller Aliases for the Models and Scripts of the left and right controllers. However, there is no simple way of getting the Oculus Avatar hand models.

I propose that when the VRTK_SDKManager is set to OculusVR (and future SDKs for hands perhaps), that it also populates its Controller Aliases with a ModelAliasLeftHand and a ModelAliasRightHand.

**Comment by bddckr** [comment]
The SDK Manager only lists stuff VRTK needs to work with. Is there something we could use the newly added info for? Otherwise we could of course _only_ add it to simplify working with the different SDKs. Are there even any other SDKs that offer hands like Oculus Avatar does?

**Comment by bddckr** [comment]
Oh maybe we'd use that with #1078?

**Comment by thestonefox** [comment]
I think at some point we need a way to provide references to other things in the oculus avatar, but we need to do it so it's generic enough that supports other things too.

For now, if you're using oculus avatar you can get your own reference to them because they're a fixed option. You don't really need VRTK to do it as there is no abstraction going on.

**Comment by reznovVR** [comment]
I would suggest closing this old issue as not much has changed, its pretty specific to Oculus and already possible via some scripting.

**Comment by thestonefox** [comment]
If we look at this when doing the SDK refactor work then I think we can achieve something useful.
