### ISSUE TITLE
Dash teleporting when grabbing onto an object that is connected to another object by FixedJoint causes grabbed object to be ungrabbed and propelled away

### ISSUE THREAD

**Issue by poopledoople** [thestonefox/VRTK#1159]
### Environment

 * Source of VRTK (Github)
 * Version of VRTK (af7ccb6 )
 * Version of Unity3D (5.6.0f3)
 * Vive
 * SteamVR

### Steps to reproduce

1. Load scene "038_CameraRig_DashTeleport"
2. Change layer on the green small cube named "Cube" to "Ignore Raycast"
3. Duplicate the green small cube named "Cube"
4. Move the new duped Cube so it's not colliding with the original
5. On this duped Cube, add a FixedJoint component
6. Set the _Connected Body_ of this FixedJoint to the green small cube named "Cube"
7. Hit Play
8. Teleport to where the two green small cubes are
9. Grab one, the other show follow as well (due to FixedJoint)
10. While grabbing, teleport to somewhere

### Expected behavior

Both green cubes should follow the player after dash teleporting. 

### Current behavior

The two green cubes are ungrabbed and propelled in the direction of the dash after teleporting. **This is not an issue when grabbing and dash teleporting with a gameobject that has no FixedJoint, that is, when it's not connected to anything.**

**Comment by poopledoople** [comment]
I should add that the grabbing mechanism is FixedJoint also.

**Comment by thestonefox** [comment]
The issue here is when you teleport, you're applying force from the second jointed object to the grabbed jointed object and it's exceeding the break force and therefore detaching.

Your options are:

 * Use another grab mechanic (e.g. child of controller)
 * Increase the Fixed Joint Grab attach break force to `infinity`
 * Do the above increase but in the `OnTeleporting` event, then reset it back in the `OnTeleported` event
