### ISSUE TITLE
Teleporter stays faded in black on Oculus Utilities

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1186]
### Environment

 * Source of VRTK: Github
 * Version of VRTK:  d4445f2505fe169e0454cbe2a11d56511efb7c9b
 * Version of Unity3D: 5.5.3f1
 * Hardware used: Oculus
 * SDK used: Oculus Utilities 1.12

### Steps to reproduce

 * Load Example Scene 004
 * Run scene and attempt to teleport

### Expected behavior

Should teleport to new location with fade in/out on headset

### Current behavior

Headset fades to black but never fades back to transparent

**Comment by thestonefox** [comment]
Works as expected using Oculus Utilities 1.13

**Comment by thestonefox** [comment]
Works with Oculus Utilities 1.14 - You need to force Unity 5.5 to use the 1.14 OVR plugin (as it only supports 1.12 by default)

**Comment by quintesse** [comment]
I see similar behaviour, but instead of staying black it just takes a couple of seconds. If I set the "Blink Transition Speed" to "0" the problem goes away.

 - Source of VRTK: Github
 - Version of VRTK: d4445f2505fe169e0454cbe2a11d56511efb7c9b
 - Version of Unity3D: 5.5.3f1
 - Hardware used: Oculus
 - SDK used: Oculus Utilities 1.14

**Comment by quintesse** [comment]
Ok, but perhaps is because I'm not forcing Unity to use 1.14? How do I do that?

**Comment by bddckr** [comment]
@quintesse [_OVRPlugin Now Included with Utilities_](https://developer.oculus.com/downloads/package/oculus-utilities-for-unity-5/)

**Comment by bddckr** [comment]
Works as expected for me using Utilities 1.13, too.

**Comment by quintesse** [comment]
Just made sure everything uses 1.14 and I still see this problem. I'll see if I can debug it.

**Comment by quintesse** [comment]
Ok, found it. It's line 61 of `VRTK_SreenFade`:

    currentColor.a = (currentColor.a > 0.98f ? 1f : currentColor.a);

that cause the problem. See what happens when I print out the values of `currentColor`,  `deltaColor * Time.deltaTime` and the resulting `currentColor` during the fade:

```
COLOR RGBA(0.000, 0.000, 0.000, 1.000) - RGBA(0.000, 0.000, 0.000, -0.012) - RGBA(0.000, 0.000, 0.000, 0.988)
COLOR RGBA(0.000, 0.000, 0.000, 1.000) - RGBA(0.000, 0.000, 0.000, -0.012) - RGBA(0.000, 0.000, 0.000, 0.988)
COLOR RGBA(0.000, 0.000, 0.000, 1.000) - RGBA(0.000, 0.000, 0.000, -0.007) - RGBA(0.000, 0.000, 0.000, 0.993)
COLOR RGBA(0.000, 0.000, 0.000, 1.000) - RGBA(0.000, 0.000, 0.000, -0.011) - RGBA(0.000, 0.000, 0.000, 0.989)
COLOR RGBA(0.000, 0.000, 0.000, 1.000) - RGBA(0.000, 0.000, 0.000, -0.007) - RGBA(0.000, 0.000, 0.000, 0.993)
COLOR RGBA(0.000, 0.000, 0.000, 1.000) - RGBA(0.000, 0.000, 0.000, -0.008) - RGBA(0.000, 0.000, 0.000, 0.992)
.
.
.
```

Each time the color's alpha gets reset back to 1.0f!

It's only when finally one frame took a little longer:

```
COLOR RGBA(0.000, 0.000, 0.000, 1.000) - RGBA(0.000, 0.000, 0.000, -0.012) - RGBA(0.000, 0.000, 0.000, 0.988)
COLOR RGBA(0.000, 0.000, 0.000, 1.000) - RGBA(0.000, 0.000, 0.000, -0.021) - RGBA(0.000, 0.000, 0.000, 0.979)
COLOR RGBA(0.000, 0.000, 0.000, 0.979) - RGBA(0.000, 0.000, 0.000, -0.012) - RGBA(0.000, 0.000, 0.000, 0.967)
COLOR RGBA(0.000, 0.000, 0.000, 0.967) - RGBA(0.000, 0.000, 0.000, -0.012) - RGBA(0.000, 0.000, 0.000, 0.955)
.
.
.
```

that the actual fade starts to happen,

**Comment by thestonefox** [comment]
https://github.com/thestonefox/VRTK/pull/1194
