### ISSUE TITLE
UI_Canvas causes lag when childed to gameobject

### ISSUE THREAD

**Issue by Belial0331** [thestonefox/VRTK#1203]
Hi, I'm new to VR and vrtk has been a great tool to learn how interactions works. I'm using version 3.1.0 in unity 5.6, using vive atc and SteamVR

At the moment I've added an in-game tablet to act as an info page, with buttons as widgets to open different sliders. So I've added a world canvas as a child of a 3d gameobject however when I activate the VRTK_UI_Canvas script it makes the games extremely laggy when I look at the object. Also the mesh freezes in place while the canvas can be moved around or lags behind it, with the script disabled the objects can be moved normally

I've resorted to deactivate the main script and manually add the components. It works fine for the sliders but I can't press buttons, I'm assuming other interactions are also disabled. I'm trying to think of a workaround with other scripts or just write something myself, but I would like to understand what's the issue here

should I invert the parenting?

**Comment by bddckr** [comment]
Check your console. If there's something getting logged repeatedly this will take down the fps a ton. If there's nothing in the console use the profile to figure out what actually takes all the time during play.

Additionally you'll have to come up with steps for us to reproduce your issue in one of the example scenes since your description doesn't explain that. The [`ISSUE_TEMPLATE`](https://github.com/thestonefox/VRTK/blob/master/ISSUE_TEMPLATE.md) that GitHub pasted into the text area when you opened this issue and you just removed and didn't bother to use is mandatory (as is said on that document).

**Comment by thestonefox** [comment]
Also, if you're using version 3.1.0 (from the Unity asset store) then it's not compatible with Unity 5.6

**Comment by Belial0331** [comment]
I though I was clear. I've added a gameobject with childed custom meshes, and a world canvas copied from vrtk, the canvas with a few buttons. With the standard unity scripts the canvas works fine but enabling VRTK_UI Canvas makes the game lag when the headset look at the object.

Aside from that the room is a single mesh with an area light and ref. probe. There were some vrtk canvases active already and it worked fine so far. Figured it was incompatability, it keeps reapeating Invalid AABB bug

**Comment by thestonefox** [comment]
@Belial0331 where did you get your version of VRTK from? The unity asset store?

**Comment by Belial0331** [comment]
originally yes

**Comment by thestonefox** [comment]
Originally? So where is it from now?

**Comment by Belial0331** [comment]
tryed the github version but was giving me errors of missing methods or cloned classes, so I was still in the one from the store

found the issue tho, forgot to clean up some files while trying to switch versions, seems to be working ok now

sorry for wasting your time
