### ISSUE TITLE
Suggestion: Climbing with colliders

### ISSUE THREAD

**Issue by mikekan13** [thestonefox/VRTK#1225]
Climbing is near broken right now if you wanted to use it in an actual game. You can pull yourself through walls among other issues. Why not have an option to keep body physics on and make it so they can't  move through walls while climbing. Like the position rewind when walking.

**Comment by thestonefox** [comment]
I don't think climbing is broken, perhaps maybe in the use case you are envisaging for it, but to say broken is a bit extreme.

As to your point where you keep body physics on so it doesn't let you pass through walls. The colliders are turned off by design to prevent you from pushing against the walls and therefore pushing the world forward around you which causes motion sickness. This idea is not a good one and I wouldn't recommend implementing it.

The position rewind works with climbing too, so if you pull yourself into a wall and release then it should rewind you back to a safe position.

**Comment by mikekan13** [comment]
Except it doesn't Almost 90% of the time it pushes you to the other side of the wall.

**Comment by thestonefox** [comment]
Which is a known issue part of this existing issue: https://github.com/thestonefox/VRTK/issues/1149

**Comment by NicholausFox** [comment]
But wait... Doesn't that mean it's broken?
I feel like breaking through a wall is kind of a big deal.

**Comment by thestonefox** [comment]
No it's not broken because it's by design.

If you can't pull yourself through a wall then when you pull yourself forward the whole world pushes back against your view (which is not realistic and causes nausia)

something is only broken if it's doing something unexpected.

**Comment by mikekan13** [comment]
Wait so bypassing walls in a game completely... Is not broken. Also, the world does push back and is quite realistic.

**Comment by thestonefox** [comment]
The world has to push back because if you physically pull yourself in the real world forward the real world does not stop when the game world stops.

**Comment by mikekan13** [comment]
If I pull myself directly into a wall I should just fall. If I'm pulling at say a 90 degree corner then my hand should slide down the wall until it can't and then I should fall. The head should never be allowed to enter the wall. Honestly the pushback that you call it feels more natural to me. I have the rewind settings set really low and use arm swinger and for walking into walls it just feels like I'm trying to walk into a wall. No nausea the world doesn't move nor do I. There should be an option for climbing to work the same way.

**Comment by thestonefox** [comment]
Feel free to raise a pull request with the additional options.
