### ISSUE TITLE
SDK_SteamVRController.GenerateControllerPointerOrigin(GameObject) requiring Occulus HMD?

### ISSUE THREAD

**Issue by Rawi85** [thestonefox/VRTK#1228]
### Environment

 * Source of VRTK: Github
 * Version of VRTK Master head(94914f07c9a5098ff6a477df03f3e3c8ef8c917c)
 * Version of Unity3D Unity 5.5.2f1 with SteamVR 1.2.0
 * Hardware used: Htv Vive
 * SDK: OpenVR

Minor Issue: My HMD is being registered as "Vive MV." instead of "Vive MV". This causes VRTK_DeviceFinder.GetHeadsetType to fallback to  Headsets.Vive instead of ViveMV.

Major Issue: GenerateControllerPointerOrigin in SDK_SteamVRController only generates a transform if the current Headset is VRTK_DeviceFinder.Headsets.OculusRift, which is obviously wrong in my understanding as when used with a Vive i get a null pointer back.

**Comment by thestonefox** [comment]
Have you tried updating your SteamVR to 1.2.1?

**Comment by Rawi85** [comment]
I have not, as the new Version of the SteamVR Plugin will most likely require a new Version of the SteamVR Runtime, which i dont have access to( Firewall blocks Steam ). 

However updating the SteamVR Plugin should only have the potential to resolve the minor naming issue and not the OcclusRift issue in SDK_SteamVRController?

**Comment by thestonefox** [comment]
I mean the SteamVR plugin for Unity which is on the Unity Asset Store, I'm assuming you can download that otherwise how would you have access to v1.2.0?

The reason I am asking you to try it is to see if that fixes the issue then it can be looked at to see if a backwards version fix is possible.

This is an issue I cannot re-create so I cannot determine if it's fixable or not.
