### ISSUE TITLE
TouchPad_Control does not re-enable constantly when using "Disable other controller"

### ISSUE THREAD

**Issue by CraigASanford** [thestonefox/VRTK#1242]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
         Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
             3.1.0 (downloaded 5/23/17)
 * Version of Unity3D (e.g. Unity 5.4.4f1)
         5.5.1f
 * Hardware used (e.g. Vive/Oculus)
           Both
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
              SteamVR/Oculus
### Steps to reproduce

 * Open the touchpad walking example scene.
 * Make sure "Disable Other controller" option is checked.
 * Start the scene.
 * When moving and releasing and allowing a few seconds between the next touch or press event the controller will re-enable properly.
 * If you quickly change direction or touch again the opposite controller will 9/10 times not re-enable.
 * So - Go straight with left controller.
 * Release and immediately pick a new direction with the left controller again.
 * Right controller will no longer work for walking.

### Expected behavior

Controllers will disable the opposite controller when using the touchpad. It will re-enable when not touching the touchpad.

### Current behavior

It will only intermittently re-enable the other touchpad. It appears that it only re-enables the other pad if you release the touchpad and not touch it again for a few seconds. However this is uncommon as normally when playing a game if you release the touchpad you normally then press it back down to change directions etc. I'm my experience so far when you press it again in any direction 9/10 it will not re-enable the other touchpad after that.

**Comment by bddckr** [comment]
I didn't check anything yet, just checking the version info with you:

> Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
> 3.1.0 (downloaded 5/23/17)

Does this mean you downloaded the 3.1.0 release from [here](https://github.com/thestonefox/VRTK/releases) or did you download the .zip from the main page (i.e. latest master) on 5/23/17?

The release section only lists the releases on the Asset Store, therefore use the latest master instead if you used the 3.1.0 release and let us know whether your issue is present on the latest master, too. ([Main page here on GitHub, right side, green button](https://github.com/thestonefox/VRTK/archive/master.zip))
(Also: The version.txt file only lists the latest release, too. So the "3.1.0" doesn't mean much if you're using the GitHub master, that's why we ask for the GitHub commit hash instead 😄)

**Comment by CraigASanford** [comment]
got it from the main github page/latest master on 5/23/17. Not sure how to get the github commit hash.

**Comment by thestonefox** [comment]
@CraigASanford can you provide the steps to reproduce in your initial post?

**Comment by CraigASanford** [comment]
Updated. Sorry.

**Comment by thestonefox** [comment]
I can't recreate this issue

**Comment by CraigASanford** [comment]
Oddly enough. Since i swapped back to my vive from oculus it doesn't seem to be an issue. So I'm wondering if it only occurs on Oculus? Maybe an issue with the axis deadzones?
