### ISSUE TITLE
Moving start position using vrtk or child objects

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1246]
### Environment
Any VRTK after new sdk setup

### Steps to reproduce
Move start position by moving VRTK object or child objects

### Expected behavior
Start position should change

### Current behavior
It does not change, still at 0,0,0

@bddckr Is this somehow intended behavior? Seem like start position is localPosition instead of position or something?

**Comment by thestonefox** [comment]
You'll need to provide clearer steps to reproduce. I don't understand what you're trying to achieve or what is going wrong.

**Comment by lambdor** [comment]
### Environment

* Source of VRTK: Github
* Version of VRTK: 067611
* Version of Unity3D: 5.6.1p1
* Hardware used: Oculus
* SDK used: Oculus Utilities 1.15.0

### Steps to reproduce

Start in 001_CameraRig_VRPlayArea and set [VRTK_SDKManager] to 0/0/10.
* Play scene using Oculus, the start position is at 0/0/10.
* Play scene using Simulator, the start position is at 0/0/0.

### Expected behavior

How do you define a start position that is valid across all devices?

### Current behavior

Currently the behavior differs between Oculus and Simulator.

**Comment by bddckr** [comment]
I think I added an example scene helper that sits on the Simulator SDK Setup and moves that Setup because the example scenes only adjust the parent `SDKSetups` game object's transform and the Simulator would then be stuck in the floor or something.
