### ISSUE TITLE
Using steam VR menu button drop grabbed object

### ISSUE THREAD

**Issue by KospY** [thestonefox/VRTK#1277]
Environment

Source of VRTK: Github
Version of VRTK: Last version
Version of Unity3D: 5.6.0f3
Hardware used: HTC Vive
SDK used: SteamVR
Steps to reproduce

- Open any scene with a grabbable object that do not need to maintain the grab button
- Grab an object
- Go to the steamvr menu using the steamvr button

Expected behavior

The object is not dropped

Current behavior

The object is dropped

Thanks for your help :)

**Comment by thestonefox** [comment]
This is expected. The issue is when you press the SteamVR button, SteamVR sets the game object that the controllers are on to disabled, this calls the OnDisable action on the script and in OnDisable it forces the drop of the object.

The reason for this is, if your battery dies on your controller then your controller would go off but you dont want the grab to stay active.

You can work around this issue in SteamVR, by adding the `[SteamVR]` prefab from SteamVR and unticking the pause on system menu option.
