### ISSUE TITLE
Getting Started doc should tie in better with the examples scenes

### ISSUE THREAD

**Issue by andybak** [thestonefox/VRTK#1419]
I hadn't read getting started for a while so I just went through it and found it curious that it got me to a point that differed considerably from 001_CameraRig_VRPlayArea 

Ideally "Getting Started" should take the user down the same road and use the same conventions as the demo scene - or another doc should go through the simplest demo scene piece by piece, explaining the structure.

**Comment by bddckr** [comment]
The example scenes are examples, *not* documentation, therefore they differ (for example in the number of added SDK Setups, we are very careful with not including the SDKSetups prefab in the "core" of VRTK, they are in the example folder for a reason).

**Comment by andybak** [comment]
I'm not sure I follow.

I'm thinking about how best to bridge the gap between "Getting started" and understanding how to construct a fully working VRTK scene. The way I've learned is via examining the examples. The main docs are useful afterwards but they are too high level to provide much help to someone who's just come to VRTK.

If my experience is common then the examples are the most realistic way currently to learn how to use VRTK.

**Comment by bddckr** [comment]
Let's reduce the confusion. 😄

The Getting Started document is explaining how to set up the SDK Setups. The resulting scene differs from the included first example scene because all the example scenes are set up to allow using any of SDKs VRTK supports.

To update the Getting Started document to explain how to list all of the SDK Setups would be a waste: People should only have the SDK Setups in their scene for which they also import the needed vendor SDKs for, otherwise Unity will tons of `script not found` warnings whenever the scene is run.

The only other difference is probably the names of the game objects, but the Getting Started document doesn't give names at all. We previously had multiple instances of people thinking there were some kind of name lookups going on there, so it's good to make sure people understand VRTK doesn't care what you're naming your things like, nor does it care for a specific hierarchy of game objects (except for the SDK Setups with respective camera rig, which the Getting Started document states).

**Comment by andybak** [comment]
Excellent. Everything you just said should be in Getting Started ;-)

More seriously - a few things in response:

1. I agree about the SDK setups. Leave them out
2. The confusion around naming is easily solved by phrasing it as a suggestion not as a requirement
3. There are other differences too - I'm currently picking through to understand what matters and what doesn't. I'll update here or do a documentation PR when I've got something more constructive to add.

**Comment by thestonefox** [comment]
Gonna close this and roll it into this new issue:

https://github.com/thestonefox/VRTK/issues/1422
