### ISSUE TITLE
Reference to 'Controller Mapper' in DOCUMENTATION.md

### ISSUE THREAD

**Issue by andybak** [thestonefox/VRTK#1420]
Line 2357:

> The Controller Events script requires the Controller Mapper script on the same GameObject

Is this out of date? There's no script named anything like "controller mapper" in VRTK currently.

**Comment by Schmork** [comment]
https://vrtoolkit.readme.io/docs/vrtk_controllerevents

Since this is closed without a comment, I reckon there _is_ a mapper somewhere. But where, I couldn't find it either?

**Comment by bddckr** [comment]
You're not looking at the latest docs, that's why. Switch to the latest version in the dropdown on the top right of that page.

Issues like these are better discussed in [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) because you can instantly get answers instead of waiting on here. It's also way easier for troubleshooting in general. GitHub issues are only useful for proper bug reports with steps to reproduce in an example scene like the Issue Template requires.
