### ISSUE TITLE
Touchpad walking while holding an object jitters.

### ISSUE THREAD

**Issue by EpicConcepts** [thestonefox/VRTK#1430]
### Environment

 * VRTK from Github
 * VRTK version from Github (3.2.1.)
 * Unity 2017.1.0f3
 * Oculus Rift + touch
 * Oculus Utilities 1.17.0

### Steps to reproduce

In example scene 17 when you pick up an object and walk with your touch controller the grabbed cube will jitter away from the way you're walking. It looks like the object is trying to follow your hand, but has a little delay, so it jumps to the position of the hand constantly.

Update: Did some more testing and found out that when the grabbable object has a snapHandle the jittering doesnt occur when walking with the touch controller. The issue must have something to do with VRTK_Fixed Joint Grab Attach as far as I can tell. When I figure out new stuff I will update this issue.

### Expected behavior

The grabbed object should move correctly with the hand without jittering or delay.

### Current behavior

The grabbed object is jittering when walking with the touch controller.

**Comment by thestonefox** [comment]
Where are you getting Oculus Utilities 1.17? Oculus Utilities is only 1.16 and that's only a beta. The only current supported version of the Oculus Utilities SDK for Unity is 1.15

**Comment by kwabbott** [comment]
I get jitter/ghosting.lag on pretty much every single object that I grab and move around in VRTK. I don't have this issue when playing games or when using Newton VR. Am I missing a setting somewhere?

**Comment by thestonefox** [comment]
@kwabbott NewtonVR uses a physics tracking object mechanism for grabbing.

If you use the Track Object mechanism in VRTK then you'll get a similar experience to NewtonVR

If you're using the joint system in VRTK for grabbing then Oculus by default runs it's physics timestep at 60fps and your HMD is updating at 90fps which is why you see the jerkiness.

You need to set your Unity Physics timestep to 1/90 to get 90fps

**Comment by kwabbott** [comment]
That worked great. Thanks!
