### ISSUE TITLE
An issue with issues

### ISSUE THREAD

**Issue by kristianpd** [thestonefox/VRTK#1515]
As a follow up to the discussion that started here: 

https://vrtoolkit.slackarchive.io/vrtk-core-development/page-21/ts-1506097357000601

I'm proposing a few changes to how we manage issues vs. ideas.

Going through the old issue list, like on any big project, can be time consuming. One of the biggest contributors to issue overload (on any project), is the idea issue. The issue list acts as a constant drag on contributors and is a turn off to new potential contributors checking out the repo. A big issue list can sometimes be a warning of a poorly maintained project; which VRTK is not.

## The idea issue
At first glance, the idea issue is a good idea. It often identifies something that is missing, or could be missing for a portion of users. It is complete enough, at first glance, to warrant consideration, but incomplete (no code) enough to actually make any progress on.

If we had a whole army of people waiting to consume each idea and prototype it, that wouldn't be a bad thing, but the truth is everyone is busy and idea issues just linger. It's very rare that someone else wants to implement your idea, you need to take the first step.

### Proposal 1: No idea issues, only PRs

Idea issues need to be replaced by PRs. The PR should be an attempt to solve the issue 

Any idea issue that is created should be labeled idea and closed, with a request from the person closing it asking the original contributor to open an PR with the idea roughed out. It doesn't need to be perfect, but it should make the attempt to start solving the issue.

I think this will help
- Reduce low effort submissions and off the cuff ideas
- Vet the idea. Many ideas seem good at first glance but fall apart when you start implementing them.
- Keep the scope of what VRTK / examples cover. There are good ideas that IMO do not warrant a merge into VRTK. These are game mechanic ideas that although they have similar core elements, end up being custom almost every time.

### Proposal 2: Triaged idea issues

Instead of requiring PRs, which may be too much for artists and designers who are not familiar with git and github, we could also have a triage system that upgrades certain issues.

New issues come in and are triaged by a contributor. If the issue is low quality, incomplete, does not have a clear suggested path for either how it can be implemented or clear details of what it needs, it's closed. If it's high quality, it can move to a voting system (emoji reactions), where people can 👍  or 👎 the idea for core contrib.  It can sit in this :+1: feature list waiting for someone to take it on, or ideally, encourage the submitter to work on it themselves.

## The issue issue

I do not have any problem with using issues for actual bugs in VRTK. These should be triaged, labeled as actual bugs (or maybe a few other labels we can warrant) and moved. 

Thoughts?

**Comment by reznovVR** [comment]
I went through some of the issues and here are few observations:

Some of them are too project specific requests. People should ask for generic events and methods so they can implement their desired feature easier instead of asking the support implemented directly in to the core features (ie. climbing stamina or strength).

Feature requests are sometimes too scarce and there should be some sort of list of minimum info required for submitting such issues and some cases a video link or a small ms paint illustration would be good on top of the text description.

Its very hard to see what the actual demand for an issue is no matter if its a bug or feature request. The github voting wont work well as people don't bother to make an account or read long descriptions. IMO we need something like a weekly slack integrated survey bot or just a strawpoll with 2-3 issues listed so people can have a say easily and we know how to prioritize time and demand efficiently. Issues are only picked to the list when enough of contributors see the issue a reasonable one and it does not mean it has to be finished ever or fast. At minimum the results could be linked to the issue if someone has time in the future or we get new contributors. Example survey/poll:

Which of the following feature requests you would like to see implemented?

1. Movement actions for flying (issue link)
2. 3D switch control (issue link)
3. FOV tunneling/vignetting as a comfort option (issue link)
4. I don't need any of these

**Comment by thestonefox** [comment]
I think it's clear to see now that there are 2 things in VRTK

Core Mechanics (e.g. grabbing, teleporting, drop zones, etc)

and

Use Cases (how to glue core mechanics together to do something)

A lot of the feature requests could be categorised as Use Cases. These Use Cases can form a different project and therefore keep VRTK core cleaner.

I like the idea of issues on here being either `bugs` (which there are already labels/states for, `investigation required` and `bug` when it's confirmed) and `feature requests` but the feature then needs to be determined if it's a use case or a core mechanic. any new core mechanic should be given reasonable time for someone to put meat on the bone of the issue, if not it goes to being `stale closing soon` then if nothing it gets closed.

**Comment by bddckr** [comment]
How are we going to move issues in case someone posts it on the core repo as a feature request, but we decide it's actually a feature request for a use case?
Copy and past, close and link to/from the other repo?

**Comment by kristianpd** [comment]
We'll move this discussion to a new issue from @thestonefox
