### ISSUE TITLE
Create generic signal/action system to allow for complex input mechanics

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1523]
At the moment any input such as a button press is a 1:1 relationship between all SDK controllers and the action it's performing (e.g. grab).

It would be better if actions are generic and can be compound to create complex sequences to initiate an action.

For example.

instead of doing Grip = Grab you could do:

If Trigger on Vive Wand or Grip on Oculus Touch then Grab

Or it could be taken further by having other complex actions such as

If touchpad axis (x/y) changed then provide Vector2

Or it could be if InputX and InputY then provide Vector2 (think of a omnidirectional treadmill input).

A branch with a very early prototype example: https://github.com/thestonefox/VRTK/tree/feat/input-actions

**Comment by bddckr** [comment]
This system could actually handle a lot more stuff. Transform actions that take touchpad axes state and return a bool to turn it into a trigger for whatever we allow triggers to be used.
The API would change to just allow `Action<bool>` for triggers, button press state is a three-valued enum, so we'd have `Action<ButtonState>` etc.

Nothing stopping us from transforming hardware treadmill input into triggers etc.

**Comment by bddckr** [comment]
Should look into [UniRx's `ReactiveProperty`](https://github.com/neuecc/UniRx#reactiveproperty-reactivecollection).

**Comment by thestonefox** [comment]
Scripts that have input:

 * Interact Grab:
   * Grab Button

 * Interact Use:
   * Use Button

 * Pointer:
   * Activation Button
   * Selection Button

 * Touchpad Control:
   * Primary Activation Button
   * Action Modifier Button
   * Touchpad axis

 * Button Control:
   * Forward Button
   * Backward Button
   * Left Button
   * Right Button 

  * Slingshot Jump
   * Activation Button
   * Cancel Button

  * Move In Place
   * Engage Button

  * Step Multiplier
   * Engage Button

  * UI Pointer
   * Activation Button (Hold/Toggle/Always On)
   * Selection Button (Click on up/down)

  * Avatar Hand Controller (probably leave this directly tied to buttons)

  * Panel Menu
   * Swipes on touchpad

  * Pointer Direction Indicator
   * Touchpad axis

  * Radial Menu
   * Touchpad touch to activate
   * Touchpad angle to select

**Comment by bddckr** [comment]
Pasting in some of my Slack messages in here:

---

Instead of having On action+Off action+Hold setting a generic way would be to have a `ToggleAction<bool>`. This class would have two "input actions", one to toggle _on_, one to toggle _off_.

`ToggleAction<bool>` is an `Action<bool>` and thus the grab script just has a public `Action<bool>`.

That way you could have like
`Touchpad Vector2 -> Angle -> Quadrant -> bool`
with
`Touchpad ButtonState -> Filter -> bool`
to have "upper left quadrant on touchpad was pressed" and "touchpad unpressed".

These would then route into ToggleAction as on and off actions.
**Boils down to "create another generic Action to hold any state".**

Also means no script needs toggle logic for example, people can just chain the actions (and we'd offer a way to share created chains).

---

And one could argue "I don't want these generic ones to return a bool" so that could just return `T2` with `resultValue` or something.

Nothing is stopping a user from having a state machine in the logic of an Action... So there could be a lot of difficult stuff being available in a generic fashion.

---

Time was one of the inputs I was thinking about...

If one were to provide a TimeAction that is more of a TimePollAction, i.e. it doesn't fire, instead you only call Get on it, then that would be a way to have different kinds of timing systems...
If actions share the same TimeAction and you change that Action (e.g. slowmotion) it will change all the Actions that use that one.

**Comment by thestonefox** [comment]
There are also a number of issues where you need to know if the button is pressed down or the button is released.

E.g. in the pointer, it can do select button pressed on button down, or select button pressed on button up.


So any input action would need to know this information.

**Comment by thestonefox** [comment]
I'm wondering if the concept of input actions for generic button presses is the best way of working?

What if SDKs had a button type, which was specific to the SDK. Then there was a proxy class that allowed you to specify which SDK button related to which VRTK button.

Then you would have something like this:

SDK_SteamVR Trigger = VRTK_Button1
SDK_Oculus Grip = VRTK_Button1

Then you just specify on Interact Grab
Grab Button = VRTK_Button1

Maybe you could also do:
SDK_SteamVR Trigger && SDK_SteamVR Grip = VRTK_Button1
or
SDK_SteamVR Trigger || SDK_SteamVR Grip = VRTK_Button1


this wouldn't help with things like where you can say "trigger to pick up" and "grip to drop" but you'd have to manually switch that in code i guess?


Any script that uses an axis, like touchpad axis could have a parameter of where it gets that axis info from maybe? And then a helper script called input axis that defines that?


I'm trying to come up with alternatives as the existing scripts may not work well with previous ideas.

**Comment by bddckr** [comment]
Action chaining:
- SDK has button types specific to the SDK (maybe change that to have its own Actions instead, to be more flexible for stuff like "there's no 'untouch' on this specific button/device at all since it only knows about pressed vs. unpressed").
- User creates a new Action that fires whenever any of the input Actions connected to it fire. I.e. boolean OR Action.

Then all you need is to set the input Actions to the SDK provided ones and set the "pick up" to the OR Action.

**Comment by thestonefox** [comment]
we could do with a prototype of the action system to prove the concept. My way of doing it is going to hit severe restrictions with how current scripts work.

**Comment by thestonefox** [comment]
Some use cases:

---------

**Interact Grab**

```
Press Trigger to grab object
Release Trigger to drop object
(this would be press and hold trigger to keep grabbing, release to drop)
```

```
Release Trigger to grab object
Release Trigger to drop object
(this would be press and release to grab, then press and release again to drop)
```

```
Release Trigger to grab object
Release Grip to release object
(this would be press and release to grab, then press and release a different button to drop)
```

```
Press Trigger to grab object
Press Grip to release object
(this would mean the trigger button would need to be held down but only drop when the grip is pressed, so this wouldn't make much sense)
```

---------

**Pointer**

```
Press Trigger to activate pointer
Release Trigger to do select action
Release Trigger to deactivate pointer
(this would be on trigger press turn pointer on, on release trigger make a selection and then deactivate pointer)
```

```
Press Trigger to activate pointer
Press Grip to do select action
Release Trigger to deactivate pointer
(this would be press and hold trigger to keep pointer on, pressing down on grip would select)
```

```
Press Trigger to activate pointer
Release Grip to do select action
Release Trigger to deactivate pointer
(this would be press and hold trigger to keep pointer on, releasing on grip would select)
```

```
Release Trigger to activate pointer
2nd Release Trigger to do select action
2nd Release Trigger to deactivate pointer
(this would on first release of trigger turn on pointer, then on second press/release of trigger would do select action and turn off pointer)
```

```
Release Trigger to activate pointer
Press Grip to do select action
2nd Release Trigger to deactivate pointer
(this would on first release of trigger turn on pointer, then grip presses would select action, then on 2nd press/release of trigger would turn off pointer)
```

**Comment by thestonefox** [comment]
@bddckr  do you think we can roll the issue https://github.com/thestonefox/VRTK/issues/875 into this one?

**Comment by bddckr** [comment]
@thestonefox Yes I guess that could be handled by the SDKs offering Signals/Actions directly. Once SDKs offer a Signal we probably can connect scripts directly with them, instead of routing through our script alias... Therefore runtime changes would be very easy.
