### ISSUE TITLE
Rigidbody interpolation causes strange drift with VRTK_ChildOfControllerGrabAttach

### ISSUE THREAD

**Issue by AaronMeyers** [thestonefox/VRTK#1556]
### Environment

 * Source of VRTK: Unity Asset Store
 * Version of VRTK: 3.2.1
 * Version of Unity3D: 2017.1.2f1
 * Hardware used: Oculus
 * SDK used: OpenVR

### Steps to reproduce

Create a cube (scale it to a handheld size... .1, .1, .1), add a Rigidbody and set the Interpolate property to "Interpolate".
Add VRTK_InteractableObject, make it grabbable.
Add VRTK_ChildOfControllerGrabAttach
Start the scene and grab the cube and shake move your arm around, paying attention to the cubes position in your hand.

### Expected behavior

The cube stays in the position it was grabbed in (precision grab or not)

### Current behavior

The cube drifts around its position.

I wouldn't have expected the interpolation of a rigid body to have any effect when its set to be kinematic, but it appears to impact it. I think that in addition to the rigidbody getting set to kinematic on pickup, the interpolation setting should be cached and set to "None" until the object is released and it should be returned to its original interpolation setting.

**Comment by bddckr** [comment]
A kinematic Rigidbody actually is not participating in the physics engine steps in Unity anymore expect when connected to joints etc.

Two ideas:
- You only added the ChildOf mechanic, but aren't actually using it because you didn't drag and drop it into the respective mechanic field on the InteractableObject's inspector.
- The Unity Asset store version is 3 months old and there have been a lot of fixes and changes since then (80 currently):
https://github.com/thestonefox/VRTK/compare/3.2.1...master
Even more (295) on the new version:
https://github.com/thestonefox/VRTK/compare/3.2.1...release/3.3.0-alpha
Update and try again perhaps 😄
