### ISSUE TITLE
avoid creating Rigidbody for Interactgrab

### ISSUE THREAD

**Issue by Jithendrakumar** [thestonefox/VRTK#1557]
Hi,

I am using Interact Grab class to grab the object using HTC Vive controllers, i have setup the environment and when i grab the object will be attached to the controller but when i release the trigger it will start falling because of Rigidbody generated at the runtime, how to avoid it. i mean how to stop generating the Rigidbody in VRTK library, do you suggest any settings??

Regards,
Jithendrakumar K.

**Comment by thestonefox** [comment]
The rigidbody on the controller that is created is a frozen constrains kinematic rigidbody which isn't going to have any effect on making the controller fall.

Interactable Objects don't require a rigidbody and one is not auto generated.

If you provide steps to reproduce your problem then it can be looked into, otherwise as this issue doesn't follow the issue template it will be closed.

**Comment by abrahampost** [comment]
I am having this same issue. when I grab an item without a rigidbody, it adds one that is affected by gravity that persists after the object is let go. My workaround was to add a rigidbody to the object and select kinematic, and uncheck "Use Gravity" and then it maintains its location after it is released. Still, it seems like there should be a way to disable the automatic creation and peristence of a rigidbody...
