### ISSUE TITLE
Gaze Pointer / Reticle Controller

### ISSUE THREAD

**Issue by prashant-naidu** [thestonefox/VRTK#1704]
Just like how we have a public gameObject for scripts associated with the LeftController and RightController, add a GazeController is active when controllers are inactive/not found

**Comment by bddckr** [comment]
What is this? A feature request?

You can use any of the VRTK scripts for gaze stuff just fine, it's just a little bit more work.

There is reason to have another script alias game object for a third controller. These only exist because VRTK needs them. You can easily create new game objects yourself in Unity.

I suggest to try your luck asking this question in [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) instead.

@thestonefox I'm voting to close this.
