### ISSUE TITLE
How old is the VRTK from GUT HUB???

### ISSUE THREAD

**Issue by nsmith1024** [thestonefox/VRTK#1900]
Today i downloaded VRTK from GITHUB, then i imported the project into unity.

Unity claims that VRTK project was created using unity 5.6, Unity is at version 2018.2 now.

Does this mean VRTK demo project was created a really long time ago?

**Comment by bddckr** [comment]
Issues like these are better discussed in [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) because you can instantly get answers instead of waiting on here. It's also way easier for troubleshooting in general. GitHub issues are only useful for proper bug reports with steps to reproduce in an example scene like the Issue Template requires.
