### ISSUE TITLE
Demos not working (so unable to work out how to use this asset)

### ISSUE THREAD

**Issue by GFLMercury** [thestonefox/VRTK#1905]
The demos are all correctly detecting oculus SDK, but I'm just a head, stuck in the floor, with no hands.

Unity 2018 2.8

**Comment by thestonefox** [comment]
This doesn't follow the issue template

**Comment by bddckr** [comment]
Issues like these are better discussed in [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) because you can instantly get answers instead of waiting on here. It's also way easier for troubleshooting in general. GitHub issues are only useful for proper bug reports with steps to reproduce in an example scene like the Issue Template requires.
