### ISSUE TITLE
Customize a class that inherits an InteractorFacade.cs Why can't objects be crawled 

### ISSUE THREAD

**Issue by wizVR-zhangjun** [thestonefox/VRTK#2147]
This is my custom class
![image](https://github.com/ExtendRealityLtd/VRTK/assets/60952586/2a62e7b7-ef6d-4d99-8b82-60a219f6add6)

This is the parameter configuration

The object cannot be grabbed while the program is running，Is something wrong?

First of all, thank the staff for their hard work, here I wish you happiness, if any great God knows what is the reason to ask me to teach me, thank you

**Comment by liuyonglzq** [comment]
Because the code determines the type of InteractableFacade, 
extending functionality through inheritance is not a good idea


![image](https://github.com/ExtendRealityLtd/VRTK/assets/17400971/6030bd63-347d-46f6-a85e-43f6c024a04c)

![image](https://github.com/ExtendRealityLtd/VRTK/assets/17400971/393e9f61-af26-4a9e-a91a-0839517935c4)
