### ISSUE TITLE
New 3D control: Keyhole

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/VRTK#387]
There should be a control that can simulate a keyhole which turns when entering the "right" key and fires events.

**Comment by kristianpd** [comment]
I also built this for my title with VRTK. I used a combination of a Hinge Joint with a snap drop zone (since putting the key in a small lock is awkward). While I'm not arguing this is a common pattern, I think the implementation will be so custom in every case that this should not be in VRTK core as a control.

I propose closing this issue.

**Comment by reznovVR** [comment]
Yeah this issue also seems kinda project specific feature. I can see it being useful to many but I would rather see this as a example scene or a PR from someone who actually used such things in various ways in their game to implement enough generic solution.

I also suggest closing this until then.

**Comment by thestonefox** [comment]
Linked to https://github.com/thestonefox/VRTK/issues/1522
