### ISSUE TITLE
Radial Menu: Lags behind controller

### ISSUE THREAD

**Issue by Vespasian** [thestonefox/VRTK#431]
For some reason the radial menu lags behind my controller when moving it fast.

(see video here:  https://www.youtube.com/watch?v=U9FSff2HTPM)

I'll investigate it some more and try to create a PR if I've got some time in the next few weeks.

**Comment by 10FingerArmy** [comment]
I believe that is a known issue with 5.4. There should be a thread in the beta forum about it pretty high up. There is also a workaround described.

**Comment by HyppoNymous** [comment]
Is Unity aware and correcting it ?

**Comment by 10FingerArmy** [comment]
For reference, the issue was discussed here. As it seems there is a solution proposed : http://forum.unity3d.com/threads/worldspace-ui-lags-behind-object-when-moved.418660/

**Comment by HyppoNymous** [comment]
> A workaround is to modify the SteamVR_UpdatePoses.cs script.. change OnPreCull to LateUpdate. This will make the controllers line up with the UI but they will be slightly more latent, so it is only recommended updating in LateUpdate when you need UI attached to the controllers.
> 
> A proper fix for this is scheduled for 5.5 where the controllers will be updated before the UI, bringing latency down.
> ​

Lining up controllers movement to UI is not good practice and you will continue introduce latency after 5.5 update, it is better letting controllers keep their native movement detection.
Or you can use render UI to texture instead, but it seems it is another Unity bug here
[](http://answers.unity3d.com/questions/997174/unity-ui-rendertexture-broken-since-501p4.html)

Also UI could be displayed only on some gameplay situations like the game "Space Pirate".

**Comment by HyppoNymous** [comment]
In "Space Pirate" game you can display a UI menu on top of guns, there is no lag when you move the controllers.
How did they done ?

**Comment by thestonefox** [comment]
https://issuetracker.unity3d.com/issues/vr-canvas-lags-behind-when-attached-to-a-controller
