### ISSUE TITLE
Colors and materials used in the examples

### ISSUE THREAD

**Issue by gpvigano** [thestonefox/VRTK#519]
When I created the example scene for my PR #345 I tried to create a more realistic environment.
I hoped that could be a first step towards a renewed set of examples (I feel disoriented each time I wear my headset and I see that white floor...), but someone got rid of this stuff just before the release 2.1!   :-(
Probably my (wasted) work had bad textured materials, but I think we can consider some guidelines that can be easily implemented to improve the scenes.

I found some hints about colors and materials reading an interesting intro to VR that Oculus published at:
https://developer3.oculus.com/documentation/intro-vr/latest/concepts/bp_intro/

_High spatial frequency imagery (e.g., stripes, fine textures) can enhance the perception of motion in the virtual environment, leading to discomfort. Use—or offer the option of—flatter textures in the environment (such as solid-colored rather than patterned surfaces) to provide a more comfortable experience to sensitive users._

and:

_Bright images, particularly in the periphery, can create noticeable display flicker for sensitive users; if possible, use darker colors to prevent discomfort._

Instead of closing or ignoring this issue I suggest to at least keep it open and in the future try to find a viable solution (e.g. less textured, but with darker materials?).

**Comment by thestonefox** [comment]
The scene was brought inline to make it more consistent, but this is a valid issue to raise because in the slack channel at the moment we're actually discussing a redesign of the example scenes because they do look very bare and potentially off putting.

Perhaps this issue can serve as the place were people put their ideas down of what it should look like.

I quite like the look of the empty warehouse in the SteamVR tutorial room, some sort of sterile room perhaps?

**Comment by kylamon1** [comment]
Maybe make the rooms have a "portal" feel to them that could give them some class, but a warehouse could also be pretty decent.

**Comment by thestonefox** [comment]
Merging into https://github.com/thestonefox/VRTK/issues/763
