### ISSUE TITLE
Controler_interactingWithPointer Demo problem

### ISSUE THREAD

**Issue by B33T** [thestonefox/VRTK#671]
Hello,
I have found a bug with the using the hand menu, Something changes the parent of the buttons. to replicate it, open the example 019_Controller_interactingWithPointer.unity. press the Menu button and aim at an item on the menu, then press the button, just as you do this release the menu button, The parent object disappears but the "button" remains.

Its hard to explain so ill try another way incase my first one sucked.
Open demo
Menu hand - Open the menu using the Menu button
Using the pointer hand point at an item on the menu (for example the color red)
Release the "pointer" pressing the button, at the same time release the menu button
repeat this very quickly multiple times (i've noticed it seems to help if i move my menu hand around a bit)

**Comment by thestonefox** [comment]
I confirmed it. It's a bizarre edge case.

**Comment by isaklilja** [comment]
I also experienced this bug. It works better when you init a new menu in each DoMenuOn and Destroy the clonedMenuObject in each DoMenuOff. But instantiating and destroying objects like this should be considered bad practice, right?

In my own implementation which has another menu-object, I saw some flickering each time I opened the menu. I solved this by using LateUpdate instead of Update for moving the menu together with the Controller.
