### ISSUE TITLE
Measuring Speed hitting Static objects

### ISSUE THREAD

**Issue by grendelbiter** [thestonefox/VRTK#690]
So I'm trying to make a choppable tree and I ran into problems trying to apply the breakable cube script. I don't want a hit to be registered if you just touch the tree that's why I'm trying to use the breakable cube script combined with the sword script. If I set the breakable cube rigidbody to kinetic there's a Nullreference exception. It does seem like it's checking the rigidbody for collision looking at this line of code: 
GetComponent<Rigidbody>().collisionDetectionMode = CollisionDetectionMode.Continuous;
Or maybe not, I have no idea where to start.

Could someone set up an example scene? I'm sorry I can't contribute with code (yet) but I could provide an Axe Model I made for the scene: http://imgur.com/yDYxwP2 
It only has 412 tris without texture filesize should be fine for VRTK.

**Comment by thestonefox** [comment]
Scroll to the bottom of this page:

https://docs.unity3d.com/Manual/CollidersOverview.html

It shows the collision requirements in Unity.

If you have two kinematic rigidbody colliders (i.e. an object with a collider that isn't a trigger and a rigidbody set to isKinematic = true) then no collision can take place.

If you set one of your colliders to a trigger, then according to that matrix a kinematic rigidbody trigger collider (i.e. an object with a collider set to trigger and has a kinematic rigidbody) will collide with another object that has a kinematic collider.

However, you'd have to check for the collision in an `OnTriggerEnter` on the object that is the kinematic rigidbody trigger collider. because the object that just has a normal collider wouldn't receive the collision.

Hope that makes sense :/

**Comment by grendelbiter** [comment]
It does thanks at least I know where to start now.

**Comment by grendelbiter** [comment]
I still can't figure it out. This is my "tree" script (a breakable cube with rigidbody set to kinematic and collider set to trigger):

namespace VRTK.Examples
{
	using UnityEngine;

	public class ChoppableCube : MonoBehaviour
	{
		private float breakForce = 150f;


		private void OnTriggerEnter(Collider col)
		{
			var collisionForce = GetCollisionForce(col);

			if (collisionForce > 0)
			{
				ExplodeCube(collisionForce);
			}
		}

		private float GetCollisionForce(Collider col)
		{
			if ((col.GetComponent<Collider>().name.Contains("Axe") && col.GetComponent<Collider>().GetComponent<Axe>().CollisionForce() > breakForce))
			{
				return col.GetComponent<Collider>().GetComponent<Axe>().CollisionForce() * 1.2f;
			}
				

			return 0f;
		}

		private void ExplodeCube(float force)
		{
			foreach (Transform face in GetComponentsInChildren<Transform>())
			{
				if (face.transform.name == transform.name) continue;
				ExplodeFace(face, force);
			}
			Destroy(gameObject, 10f);
		}

		private void ExplodeFace(Transform face, float force)
		{
			face.transform.parent = null;
			Rigidbody rb = face.gameObject.AddComponent<Rigidbody>();
			rb.isKinematic = false;
			rb.useGravity = true;
			rb.AddExplosionForce(force, Vector3.zero, 0f);
			Destroy(face.gameObject, 10f);
		}
	}
}

When I hit the cube with the Axe nothing happens. I have to hit another rigidbody first and if I just touch the cube then it explodes. I'm guessing I would have to change OnCollisionEnter on the axe script to OnTriggerEnter too. I can't measure the speed with OntriggerEnter though, there is no comparable command to relativevelocity.magnitude.
Another thing that bothers me with this setup is that I have to set the collider on the tree to trigger. That means I can walk right through it. I tried adding another collider but then there's a Nullexception. Please help me set this up.

**Comment by thestonefox** [comment]
I think this question is better off asked in the slack chat http://invite.vrtk.io as it doesn't seem to be an issue related to VRTK and more a general Unity issue.
