### ISSUE TITLE
Headset collision / fade with script/tag policy fails

### ISSUE THREAD

**Issue by CraigASanford** [thestonefox/VRTK#701]
Easily recreated. 

Lets say you have a sphere on your (eye) object. This sphere has a tag of Sphere.
You add headset_collision and headset_Fade then add a Script or Tag List Policy to your headset collision with the Sphere tag in the list and set to ignore.

When you start the scene you will be able to see just fine as though the list policy is working. But as soon as that ignored sphere collides with something else NOT on the list policy your headset fades. Even though the headset itself does not collide with anything.

**Comment by thestonefox** [comment]
This is because the sphere you've added as a child of the headset will become a valid child collider for the headset.

If you have a sphere with a sphere collider on it and no rigidbody, the sphere collider will propagate any collision back up to the highest object which will be the headset.

The solution would be to add a rigidbody to your sphere (make it kinematic = true) then the collider propagation wouldn't happen,
