### ISSUE TITLE
Please add example of use via pointer click

### ISSUE THREAD

**Issue by blumunky** [thestonefox/VRTK#743]
Example '019_Controller_InteractingWithPointer' shows how to use an object by pointing at it, but it is constantly 'used' whenever the pointer is on the capsule.  Could you add another capsule to that example which only spins when you point at it AND click the touchpad?

**Comment by thestonefox** [comment]
To activate something with a pointer on click you would have to change the Pointer settings to have "hold button to activate" as unchecked:

![image](https://cloud.githubusercontent.com/assets/1029673/21045970/5705b34a-bdfa-11e6-81fd-d5e97fbfccbe.png)


This then performs the activation when you release the touchpad (i.e. on click) rather than whilst holding it down.
