### ISSUE TITLE
VRTK updated  errors

### ISSUE THREAD

**Issue by MarkTheLily** [thestonefox/VRTK#766]
I just downloaded VRTK master today, opened new project to test if it worked.
I added touchpadmovement on camrig and actions on hand .
I got this error
NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_TouchpadWalking.Move () (at Assets/VRTK/Scripts/Locomotion/VRTK_TouchpadWalking.cs:133)
VRTK.VRTK_TouchpadWalking.FixedUpdate () (at Assets/VRTK/Scripts/Locomotion/VRTK_TouchpadWalking.cs:144)
After I opened it, it specified this:
 code var movement = deviceDirector.forward * movementSpeed * Time.deltaTime;
same errors came up on climb 
Also none of the examples work
its gave me this error
VR: OpenVR Error! OpenVR failed initialization with error code VRInitError_IPC_ConnectFailedAfterMultipleAttempts: "Shared IPC Connect Failed After Multiple Attempts (308)"!

**Comment by thestonefox** [comment]
Did you follow the new install instructions? 

Download steam vr plugin 

Add the vrtk sdk manager script and select steam vr for the sdk.

Then drag over the relevant linked objects

**Comment by MarkTheLily** [comment]
You're right I haven't seen new instructions.
But after adding climb it still puts play in ignore raycast even if I change snap to floor settings.
It always keeps it in raycast.
+ for some reason, I have to let go of first controller grab for second controller to grab the wall while climbing

**Comment by thestonefox** [comment]
If you want the CameraRig not to be added to the `Ignore Raycast` layer then you need to change the layer to something other than Default. 

The CameraRig needs to be on a layer that is also configured to ignore the relevant raycasts from the other scripts.

Objects now need a secondary grab action on them to determine what happens if you grab with another object.

If you haven't added a secondary grab action, then the second controller grab won't do anything. It sounds like you want the Controller Swap secondary grab action.

**Comment by MarkTheLily** [comment]
on what do I put VRTK_SwapControllerGrabAction on?
I tried camera rig both hands, single hand, none worked

**Comment by MarkTheLily** [comment]
Yep it worked, Thanks
