### ISSUE TITLE
This might not be VRTK issue but its an unity issue and specially VR issue.

### ISSUE THREAD

**Issue by MarkTheLily** [thestonefox/VRTK#771]
I have a problem with Physics frame rate. Sometimes spheres don't detect collision, sometimes they do. Its not just little things, its a big problem, I'm trying to use vr controllers and my sword just goes through the collision, if I swing bit fast.

I don't know how to put the codes and scripts that don't even use void Update into void FixedUpdate.
Also what about physical items which aren't even mentioned in scripts how do we speed that up?
Does anyone know how to change, Time manager setting so it won't mess up collision detection so bad?

**Comment by thestonefox** [comment]
@MarkTheLily if you find your objects are being swung fast and not colliding with other things then it may be the grab mechanic type you've selected. The `Track Object` grab mechanic is the best for dealing with fast moving collisions.

**Comment by MarkTheLily** [comment]
I'm not using VRTK script at all
https://www.youtube.com/watch?v=pX3xQg1puRE
Does track object works with raycasting?

**Comment by thestonefox** [comment]
Track Object doesn't use raycasting, it uses physics velocity to move the object around so rigidbody collisions within unity should be as good as unity can provide.

Raycasting can be quite expensive so it's not offered due to performance issues but it would be possible to extend an Interactable Object script and add raycasts to the update routine to check for additional collisions.

This performance hit would then be in specific game code rather than the framework code.

**Comment by MarkTheLily** [comment]
I will try to test VRTK TrackObject tomorrow
Take a look at this, tell me how bad is it?
https://www.youtube.com/watch?v=lNsTSW04G1Q&t=30s

**Comment by MarkTheLily** [comment]
No its just empty object with rigbody (continuous dynamic )is attached to controller via fixed joints.
swords spawns in empty

**Comment by songjiekun** [comment]
> No its just empty object with rigbody (continuous dynamic )is attached to controller via fixed joints.
> swords spawns in empty

 i face a similar issue.  if i swing sword quick, i will miss my object sometimes. especially when hit a thin object , for example hit another sword.
