### ISSUE TITLE
Dont rely on physics timing for touching objects

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#779]
In the VRTK_InteractTouch script, OnTriggerStay sets triggerIsColliding, but assume that OnTriggerStay is not run for 3 frames (since its not on the same timer as Update),
this will mean that after 2 frames, both triggerWasColliding and triggerIsColliding will be false, and the 3rd frame, it will enter the first if case, and also the second one since its only being touched so "touchedObjectScript.GetGrabbingObject() != touchingObject" will be true. This will trigger StopTouching. And next frame it will notice that its not touched and start touching it again causing an endless loop of flicker.

i did some tests and it seems like i get a lot less OnTriggerStay compared to LateUpdate in my project, which seems to confirm my theory, also tried to reduce the Physics timestep and it reduced the flicker rate which also seems to confirm it.  I also tried lowering the timeStep slightly in the VRTK project and i got the exact same flickering.

**Comment by virror** [comment]
Found a potential fix for this, the idea here is to make sure that all setting of the triggerWasColliding and triggerIsColliding should be in the same "timeStep", while the use of them can still be anywhere.
So the fix is to just move:
triggerWasColliding = triggerIsColliding;
triggerIsColliding = false;
From the end of LateUpdate() to the end of OnTriggerStay.

**Comment by thestonefox** [comment]
If you move `triggerWasColliding` and `triggerIsColliding` into the end of `OnTriggerStay` won't that mean they're always false when the `LateUpdate` is called?

The point of the `LateUpdate` check (as far as I can remember) is a final end of frame check to see if the controller colliders have come away from the object (due to any unity physics glitches)

I really need a way of recreating your issue so i can see where it's going wrong :(

**Comment by thestonefox** [comment]
PR https://github.com/thestonefox/VRTK/pull/788

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/2c22050ef363a2f3060849c3508a472c30ee223c
