### ISSUE TITLE
Adaptative quality bug

### ISSUE THREAD

**Issue by FairT** [thestonefox/VRTK#780]
Hi,

When we use in the draw debug visualization in the Adaptative quality script we got this error :

"Fallback Headset SDK is being used. Have you selected a valid Headset SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Headset SDK from the dropdown."

This bug was not present the 22th of December.

If we uncheck this option everything runs smooth.

Also, I don't know if it is the right place to talk about it but in the "Move In Place" script if we select as Control Options "Headset only", while we walk in place if we look from down to up the speed highly increases.

It is causing sickness, it would be a lot better if only the headset Y value would be taken in account.

Again, not the right place, but I want to thank you guys for the huge amount of work you're doing and to share that with the community, you are half gods.

And you are lucky that I don't know you otherwise I'd kiss you, which is the worst part.

Take care, and thanks again.

**Comment by thestonefox** [comment]
First bug has been fixed in commit: https://github.com/thestonefox/VRTK/commit/ea76402213939c81fcb2ed38c280cb65d263679f

The second issue regarding the headset movement.

The movement is based on the Y position of the headset changing. if you nod your head then the Y position will invariably change because the central point of origin on the headset is moving up and down when you nod.

I had a quick look at seeing if it was possible to set the speed to 0 if the Y changes caused by a nod were under a certain threshold, but this then also prevents you from walking with a gentle headbob.

One solution may be to check the rotation of the headset and if it's not looking roughly straight forward then ignore the Y delta it gives. But then this may also have issues if you're running and looking up or down (as it would then stop the user running because they're exceeding a rotational threshold).

**Comment by FairT** [comment]
Thanks for your explanations, it makes sense.

Take care :-)
