### ISSUE TITLE
Create SDK switcher to allow for switching between SDKs at runtime based on headset plugged in

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#817]
There should be a default way within the toolkit to allow devs to switch SDK at runtime.

**Comment by dantman** [comment]
Some VR games on Steam use a "Open in Steam VR" / "Open in Oculus VR" Steam radio box launcher. Which presumably just makes Steam run the executable with different arguments. So besides just auto detecting available headsets it might be good to also support arguments to explicitly pick an SDK.

Also because Unity generates warnings when you have multiple VR camera rigs from different SDKs (I get a stream of errors about multiple audio listeners when I have both the Steam VR camera rig and the VRTK Simulator in the same scene) we're probably going to have to auto-spawn the camera rig from prefabs instead of dropping instances in scenes. Presumably by dropping links to the Steam VR [CameraRig], Oculus rig and avatar, and Simulator (or a copy of them) into the SDK Manager. 

The biggest issue I can imagine is customizing SDK rig settings (Steam VR's bounds colors and sizes, Oculus Avatar's displaying of hands and/or controllers). Right now if you drop a prefab instance into a scene the overrides will be in the scene and the instance will be linked to the prefab in the SDK. So when you update, any changes to the SDK's prefabs will update in all scenes and setting changes will persist in the instance. However if you instead spawn the SDK's prefab and edit the SDK's prefab settings directly, then updating the SDK may delete your setting changes. And if you make your own prefab, then when you update the SDK changes to it may not apply to your prefab. Although I may be overstating this problem, in theory you're supposed to be making your own prefabs anyways, so there are probably a bunch of people that already use unlinked prefabs of their own with settings changes for Steam VR's [CameraRig] and just workaround the caveats.

**Comment by linojon** [comment]
This probably wont fit into the VRTK architecture but, our solution in other projects is to put device specific rigs in separate sub-scenes and then load the scene we want at runtime.

**Comment by thestonefox** [comment]
Maybe the end solution to this could be a collection of tutorials showing different ways of how to set it up in your own project?

**Comment by dantman** [comment]
Another idea could be to add some extra VRTK scripts that instead make VRTK responsible for tweaking some of the rig settings you tweak most commonly; or replacing a SDK level feature with a user/VRTK level feature that we might be able to customize more. Then unmodified standard prefabs are enough for most users and only people with more uncommon/complex use cases need to deal with keeping their own prefab up to date.

The simple version would be something like a `VRTK_ControllerDisplay` script with settings like "Start With Controllers" and "Hide Hands" (or a better pattern of settings I can't think of) which would simply modify the "Start With Controllers" setting and optionally disable hand models in the standard Oculus Avatar prefab. So all you need is SDK prefab + settings script.

A more complex example would be a `VRTK_PlayArea` or `VRTK_Boundaries` script you could add alongside the SDK Manager. Then, instead of having to modify the boundary thickness and color in the `SteamVR_PlayArea` script on `[CameraRig]`, the script would implicitly hide the play area boundaries that come with the SteamVR prefab, fetch the play area metadata in an SDK agnostic way and draw its own play area boundaries. Then we'd have the same boundary rendering in SteamVR and OculusSDK; and there would even be room to support optional extras like 3d mesh based boundaries, floor textures, particle lines, or any other type of custom boundary drawing that fits into the theme of the game better.

**Comment by bddckr** [comment]
[My PUN Test project](https://github.com/bddckr/VRTK-PUN-NetworkTest) does include an "SDK Chooser" now. Have a look.

**Comment by linojon** [comment]
We do it with separate config scenes for each device that is additively loaded at runtime after the platform detection is made. Using subscenes to make it modular.

**Comment by bddckr** [comment]
Yeah I stole that for the test project 😛

**Comment by treefortress** [comment]
Ideally, we could just have multiple VR rigs under the VRTK root, and it just auto enables the correct one at runtime. That allows us to configure/customize each VR rig as we need, but we don't need to get into funky additive loading, or other workarounds.

VRTK
 -> SteamVRRig
 -> OculusVRRig
 -> PSVRRig
etc...

Create a small script that can be placed on each rig to identify it's hmd, and controls. Then SDK manager only needs a reference to each hmdSet, and can flip the correct one on at startup.

True that your prefab wont be updated when the SDK updates, but that's a fact of life already. The first thing you do in any VR project is duplicate the prefab so you can customize it. I don't see this as a primary concern.

**Comment by bddckr** [comment]
@treefortress Said "small script" could actually be the SDK Manager.
You set up multiple ones of them for the associated SDK+CameraRig, then the one you enable takes care of the rest like loading the VR device, activating the CameraRig etc.
We could even allow reverting everything it did when it's disabled.

I'll have something like that up soon as I can adapt my PUN Test project code for that.

**Comment by treefortress** [comment]
Yep that works too :)

**Comment by dantman** [comment]
It's probably better for the script connected to the camera rig to be separate from the SDK Manager.

There can still be multiple SDK types selected (eg: The HMD SDK and Controller SDK can be different). And in the future this will be a requirement (Locomotion SDKs will always be different, and they also won't have a camera rig).

It's probably best if we have a smaller script responsible for being assigned one SDK type, linking to the camera rig. While the SDK manager is responsible for linking to the aliases and the correct VRTK_CameraRig component(s).

Also it's probably better if these scripts don't have to be on the rig itself. There might be some SDKs similar to OculusVR where they are actually composed of 2 separate SDKs and rigs and might need a container. Or instead of replacing the standard camera rig prefab someone might just want to put their VRTK_CameraRig components on `[VRTK]` instead of on the rigs themselves.

**Comment by bddckr** [comment]
I'm working on it by splitting the SDK Manager into pieces first. The `Load` button in the inspector will just call a method on the SDK Manager that is also available at runtime. There will be an `Unload` method, too.
The idea is to add more fields to the Setups so the SDK Manager knows which VR Device (or none) to load and the associated game object(s) to enable/disable or spawn/destroy.

---

![WIP](https://cloud.githubusercontent.com/assets/294347/24076763/578f8d30-0c39-11e7-98e9-30d23f6c2d74.png)

**Comment by bddckr** [comment]
I'll have a look at simplifying things into one SDK dropdown (we can't load the VR Devices `OpenVR` and `Oculus` at the same time anyway...).

**Comment by dantman** [comment]
> we can't load the VR Devices OpenVR and Oculus at the same time anyway...

That's not necessarily completely true and there are more SDKs than just OpenVR and OculusVR to think of. It's still possible that there will be situations where support for either multiple SDKSetups or a mixed SDKSetup will be desirable.

* Remember that OculusVR is actually made up of two separate SDKs on its own (the SDK for the HMD and the Avatar SDK for the controllers), it's not unreasonable for a different controller SDK to be used.
* Remember we're supporting a bunch more SDKs in the codebase, PRs, and some private SDK implementations: Daydream, Ximmerse, and Gear VR (even PSVR would be nice as well). With the number of controllerless mobile SDKs there it would be reasonable for them to be used with a different controller SDK.
* Don't forget about the Nolo VR SDK, which provides controllers and additional tracking for mobile VR SDKs.
* #992 asks for support for new Locomotion SDKs (Treadmills, Walk in Place hardware like VAY and PocketStrafe) which are going to require an additional SDK selector that cannot be combined (since no VR SDK provides a Locomotion implementation and no Locomotion SDK provides a HMD or Controller implementation).
* Additionally glove controllers are going to be coming out. Judging from the implementations I've seen so far, it looks like most of them will be doing that through their own SDKs as well rather than attempting to get OpenVR to integrate them. Which means, a separate Glove SDKs selector.

**Comment by bddckr** [comment]
I was talking about actual VR **Devices*, you're talking about SDKs. I agree that we need to support using different SDKs at the same time, but if a user specifies to use SteamVR for the HMD and Oculus for the controllers it makes no sense.

I was only talking about the that specific use because we're building upon Unity's native integration of the runtimes and therefore are bound to be only to load one of those VR Devices at the same time via [`VRSettings.LoadDeviceByName`](https://docs.unity3d.com/ScriptReference/VR.VRSettings.LoadDeviceByName.html).

**Comment by bddckr** [comment]
I'll make sure to let the SDKs specify their "native VR Device" so I can tell the user about SDKSetups that are not possible.
