### ISSUE TITLE
Include current unitypackage file in repository

### ISSUE THREAD

**Issue by linojon** [thestonefox/VRTK#829]
It'd be convenient to have a current .unitypackage exported at the root of the project in github

**Comment by thestonefox** [comment]
The latest releases should always be on the unity asset store, and making an updated package for every new commit to master is a pain because of git merges

**Comment by bddckr** [comment]
It's easy enough to copy the `Assets/VRTK` folder I think. I agree that updating the package will become a pain.

**Comment by quintesse** [comment]
Besides the fact that it's not a good idea to commit binaries that change a lot.

**Comment by linojon** [comment]
ok so the recommended update process is to do a git pull from github into a local clone of the repository, then copy the Assets/VRTK/ directory into an existing project?

**Comment by thestonefox** [comment]
The way I do it is (and I'm not saying this is the best way! :p)....

 * I git clone VRTK into it's own directory
 * I then create a new unity project
 * I then create a symlink to the VRTK/Assets/VRTK directory into my new project MyNewProject/Assets directory

This means that I can just do git pulls from VRTK master to get updated changes in my new project.

**Comment by thestonefox** [comment]
Any other views on this subject or should we close the issue?

**Comment by burnedikt** [comment]
Personally, I like the use of git submodules since the contents of any package like VRTK do not need to be stored in the project's repository but are just referenced. Basically like the symlink solution, just cross-platform and automatically integrated with git. 

However, due to the surrounding project in this repo, this is not the most viable option, since we'd only need the Assets/VRTK folder + licenses and none of the ProjectSettings or other stuff.

The option with the highest reusability would probably be to have two repositories: 

- one which solely contains the VRTK core and can be inlcuded as a submodule in any project
- another one which holds the sample project and includes the VRTK core as a submodule. 

That way, the growing list of examples could also be outsourced to the example project repo.

**Comment by thestonefox** [comment]
@burnedikt that's not actually a bad idea to have the core VRTK in one repo and then another repo which is the project with a sub module to the core VRTK repo.
