### ISSUE TITLE
VRTK_InteractControllerAppearance Hide Controller on Grab not working

### ISSUE THREAD

**Issue by moscartong** [thestonefox/VRTK#838]
# Problem
## Description
Controller won't hide when grabbing object despite VRTK_InteractControllerAppearance "Hide Controller on Grab" is set to true.

## Versions
* Unity : 5.5.0f3
* VRTK : 3.0.0
* SteamVR : 1.1.1

## How to repeat the problem ?
1. Install SteamVR and VRTK from assetstore.
2. Setup VRTK_SDK Manager and controller script alias:
<img width="372" alt="1 vrtk_sdk manager" src="https://cloud.githubusercontent.com/assets/165961/22092070/021fe696-de36-11e6-9424-ddecca4b3b2c.png">

3. To both controller's script alias gameobject : add VRTK_InteratGrab script to allow controller grabbing objects; add VRTK_InteractControllerAppearance script and check "Hide Controller On Grab":
<img width="373" alt="2 vrtk_interact controller appearance" src="https://cloud.githubusercontent.com/assets/165961/22092069/021fac12-de36-11e6-831c-87ae284d026f.png">

4. Add VRTK_InteractableObject to gameobject:
<img width="374" alt="3 vrtk_interactable object" src="https://cloud.githubusercontent.com/assets/165961/22092071/022b4446-de36-11e6-852b-e1a566a9d880.png">

5. Try grab the gameobject with controller.
6. The controller is still visiable when grabbing the gameobject.

Did I miss something or set something wrong?

**Comment by thestonefox** [comment]
You haven't set a grab attach mechanic so the grab action never happens.

**Comment by themattler** [comment]
![capture](https://cloud.githubusercontent.com/assets/8305353/22136550/23467016-dea3-11e6-93d7-7d68c2dfbaa3.PNG)

None of hide on touch, hide on use, hide on grab are working for me.

I believe this issue is in the method ToggleControllerVisibility in each of VRTK_InteractGrab.cs, VRTK_InteractTouch.cs, VRTK_InteractUse.cs

Specifically, 
```
if (grabbedObject)
{
    var controllerAppearanceScript = grabbedObject.GetComponentInParent<VRTK_InteractControllerAppearance>();
     if (controllerAppearanceScript)
     {
         controllerAppearanceScript.ToggleControllerOnGrab(visible, controllerActions, grabbedObject);
      }
 }
```

It's checking for the presence VRTK_InteractControllerApperance script on the grabbed object, but shouldn't it be checking for the presence of the script on the controller?

**Comment by themattler** [comment]
I've confirmed that changing 
```
var controllerAppearanceScript = grabbedObject.GetComponentInParent<VRTK_InteractControllerAppearance>();
``` 
to
 ```
 var controllerAppearanceScript = GetComponentInParent<VRTK_InteractControllerAppearance>();
```
fixes the problem, (similarly for InteractUse and InteractTouch)

**Comment by thestonefox** [comment]
You're supposed to attach the `VRTK_InteractControllerAppearance` script to the Interactable Objects that you want to affect the controller appearance with. You're not supposed to put it on the controller.

**Comment by quintesse** [comment]
A couple of remarks because this has happened to me a a couple of times too:

 - put this dependency clearly in the docs
 - put this dependency clearly in the comments at the top of the script
 - couldn't we put a Unity editor annotation that this script depends on InteractableObject?
 - wouldn't a change of name make this perhaps more clear? Ie name all interact scripts that go on the controller `InteractXxxx` while all that go on objects `InteractableXxxx`, so `VRTK_InteractControllerAppearance` would become `VRTK_InteractableControllerAppearance`

**Comment by thestonefox** [comment]
I should have linked the new Issue before closing this one :)

https://github.com/thestonefox/VRTK/issues/848

**Comment by quintesse** [comment]
Heh, I'll copy the last remaining item in the list so you can comment on it there :)
