### ISSUE TITLE
Ensure momentum in Move In Place script is carried on when the activator button is released

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#853]
At the moment if you have momentum using Move In Place and then release the activator button, you come to an abrupt halt which is jarring.

It should keep the momentum going and decelerate.

**Comment by SuperSonic68** [comment]
Seconded on that. 

This issue is especially noticeable while airborne. While it feels great to crank the run speed, run off of a ramp and rocket off of it, it does NOT feel great to let go of the button during the jump, as you will stop instantly and plummet to the ground. Additionally, I should NOT be able to manipulate my speed and direction while airborne either. 

Running off of a surface should result in the momentum being carried off of the surface with physics taking over entirely, regardless if the player is holding the run button, or not.

**Comment by thestonefox** [comment]
PR https://github.com/thestonefox/VRTK/pull/902
