### ISSUE TITLE
Object Auto Grab a prefab -> Grab does not hide Controller

### ISSUE THREAD

**Issue by proepkes** [thestonefox/VRTK#856]
I used the Gun from an example-scene and made a prefab out of it, then did the following:

1) Attach VRTK_Object_Auto_Grab to Controller
2) Choose gun-prefab and set it to "Object to Grab"
3) Check "Clone Grabbed Object" since the object is a prefab
4) Make sure the gun has "Hide Controller on Grab" checked
5) Play
(optional) 6) If the Attach-Mechanic is "ChildOfController", then the gun will be kinematic after StopGrab, even though the prefab is not kinematic

The gun gets correctly attached to the controller, but the controller will not hide. 
If I uncheck "Disable When Idle" I get the correct behaviour, but I'd like to keep that feature enabled too.

I guess the problem is in VRTK_InteractableObject.Awake(), line ~645:

if (disableWhenIdle && enabled)
            {
                enabled = false;
            }
I think this should be somewhere else because it is possible that the object is not idle when awake

**Comment by thestonefox** [comment]
I think this can be fixed by just forcing `disableWhenIdle` to be true at the start of the auto grab script, then resetting it to the saved value at the end of the script.

The line in the InteractableObject Awake method is required to ensure it's turned off if it's supposed to be. Doing it any later will mean it's been enabled already.

I'll do a pull request and you can check out the work.

**Comment by thestonefox** [comment]
Here's the pull request for it: https://github.com/thestonefox/VRTK/pull/859

I've had to add a specific flag to determine if you're using a prefab or not, because it seems the prefabs behave differently!

Anyway, this PR should fix the issue and it has a commit in there as well to fix the kinematic issue on drop as well.
