### ISSUE TITLE
Adaptive Quality is causing artifacts with oculus devices on steamVR

### ISSUE THREAD

**Issue by TMaloteaux** [thestonefox/VRTK#858]
Adaptive Quality is causing artifacts with oculus devices on steamVR. No problem with the same build and my Vive.  
Launching the game with -noaq argument solve the problem.

**Comment by bddckr** [comment]
Do you have `Scale Render Target Resolution` checked on the Adaptive Quality script? If so, try unchecking it.

Otherwise I'd assume that the SteamVR/OpenVR methods AQ uses are probably not working for the Rift under SteamVR. VRTK's SDK implementation for Oculus handles those method correctly as far as I can see, but I guess it would be too much work to offer a build of your game using Oculus SDK.

Therefore I commented out those methods and it should still work fine in the Vive but could potentially fix it for the Rift: https://gist.github.com/bddckr/85876cf374cde76db3a115ca0aca65b6 AQ should probably offer to allow to disable the usage of those methods anyways.

- If it works for you we probably should tell Valve about it so they can fix it in SteamVR/OpenVR.
- If it doesn't work on the Rift with this I guess Unity is at fault. There were tons of problems with the render scales in almost every other release they did. **Unity 5.5.0p4** has a fix mentioned in their release notes for this, so if you don't use it yet, try upgrading to that one.

Another idea could be to just use Oculus' adaptive resolution instead of VRTK's AQ on the Rift for now. Search for "adaptive" [here](https://developer3.oculus.com/documentation/game-engines/latest/concepts/unity-utilities-overview/). But I think this requires you to switch to use the Oculus SDK instead of SteamVR for the Rift.

Good work on using `-noaq` for a quick workaround. That will still work with the modified AQ script above.

**Comment by TMaloteaux** [comment]
Thanks for you help. Unfortunately nothing worked to solve my issue.
I will probably add oculus sdk support on the future.
