### ISSUE TITLE
Scripts with co-routines on script alias controllers (at start)

### ISSUE THREAD

**Issue by JamesHunter-DeepVoodoo** [thestonefox/VRTK#878]
I've an interesting issue :) I have special scripts on the controllers, mostly to handle controller UI, etc. A certain script builds 3D text by splitting the pixel processing over a few frames (using coroutines).

The script will start this processing coroutine in start() or awake() - and I noticed coroutine fires and executes the "yield" - However this never returns (so the next line is never executed). The object is not disabled or deleted by myself appears happy in the hierarchy.

Btw, this worked fine in 2.x but not in 3.0

I think it may be because the object containing the script (or it's parent) is becoming detached and reattached in the moved from [VRTK] to the real cameraRig - but I can't see the code that handles this.

I can "fix it" by waiting until the move is complete (atm it's a messy wait for 10 frames in Update() then kick off the building coroutine).

**Comment by bddckr** [comment]
If you are talking about the script alias controllers being parented to the actual controllers:
`VRTK_SDKManager.Awake` calls `VRTK_SDKManager.SetupControllers` which add the component `VRTK_ControllerTracker` to the script alias controllers.
`VRTK_ControllerTracker` in turn parents the alias controller to the real controller **in the `Update` method**.

You could do `yield return new WaitUntil(() => transform.parent == VRTK_DeviceFinder.GetActualController(gameObject).transform);`. That should only continue the Coroutine when the parenting is done.

A real fix would probably be to find out why `VRTK_ControllerTracker` is doing the parenting not until the `Update` method is run... Especially because it seems wasteful having that `if` there run *all the time*.

**Comment by thestonefox** [comment]
The reason it's done in the `Update` is because SteamVR streams the controllers in on runtime and they're not available in Awake, OnEnable or Start.

There is an event on ControllerEvents called `ControllerEnabled` that is emitted when the controller is setup. You could listen on that event and do the stuff required.

That should work i think.

**Comment by JamesHunter-DeepVoodoo** [comment]
Thanks guy's, I'll see about implementing the event based solution!
