### ISSUE TITLE
VRTK_InteractableObject and GrabOverrideButton

### ISSUE THREAD

**Issue by JamesHunter-DeepVoodoo** [thestonefox/VRTK#883]
I was debugging an issue with picking up any interactable objects when I moving fro 2.x to 3.x 

It would appear that setting "GrabOverrideButton" to "Grip_Click" (instead of undefined) stops the grab from working with the Grip's click but only if the SecondaryGrabActionScript is null in the editor (this is what how I figured out how to reproduce it in example 005)

For some reason the upgrade set all my interactable objects to this (instead of undefined which iirc they were originally)

From what I can see the grip "click" is not getting into the interactable object.

If you need any further information let me know!

**Comment by thestonefox** [comment]
The reason your overrides were updated was because the button enum positions changed.

Are you saying grip click doesn't work? I think grip click only works on analogue grips like on the oculus touch. I wonder if steam vr supports an axis for grip now.

**Comment by JamesHunter-DeepVoodoo** [comment]
I didn't realise that "grip_clip" wasn't available on the Vive's, I had just assumed it fired when the grip button was clicked; this is what probably threw me off the longest (given it looked like it should be correct)..

Happy to close this if you feel that answers the issue :)

**Comment by thestonefox** [comment]
Yeah I can see why it's not working now.

In ControllerEvents, the click events (Trigger/Grip) are thrown when the button axis reaches it's threshold (e.g. 1f)

But SteamVR SDK Bridge always reports the Grip axis threshold as 0 which is why Grip click doesn't work for SteamVR.

Although I need to look into this further, because if SteamVR doesn't have an axis for the grip button (which may well be the case) then the Oculus touch grip axis isn't going to work on SteamVR either.

**Comment by thestonefox** [comment]
It would seem that SteamVR has 5 axis on the controller but all relate to the trigger or touchpad (?!)

So it seems there is no grip axis on SteamVR meaning Grip click would be unsupported.

https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Scripts/SteamVR_Controller.cs#L23-L27

https://steamcommunity.com/app/358720/discussions/0/487876568226759993/
