### ISSUE TITLE
SteamVR Plugin Interactions Example Parity and Replication

### ISSUE THREAD

**Issue by dantman** [thestonefox/VRTK#887]
The `SteamVR` Plugin has its own `Interactions Example`:
https://www.reddit.com/r/Vive/comments/5qpazi/check_out_this_latest_update_to_steamvr_that_lets/

Even though VRTK's systems are more featured, flexible, and available to more platforms it looks to someone quickly looking as if the interactions system primarily the teleporter in the `SteamVR Plugin` is the more polished system. Simply because of the visual assets included in the sample by Valve.

If there are any small touches or interactions that VRTK is missing it would be useful to implement them. For example it's not immediately obvious how an equivalent to teleport points would be made. The 3rd lock state is also not a simple checkbox.

Then we can create an example that works exactly like the `SteamVR Plugin` `Interactions Example`. And we can link to the assets in the `SteamVR Plugin` so this example has the same polish.

**Comment by thestonefox** [comment]
Everything in the SteamVR plugin is re-creatable in VRTK (even the visual polish).

On one hand I think updating the examples and polish is a good idea because it makes people see what can be achieved (there is an outstanding issue for this: https://github.com/thestonefox/VRTK/issues/763)

Playing devils advocate, I'm also dubious that nice looking assets in the toolkit will just spawn a bunch of games where people cba to change the assets.

I expect now we'll see a flurry of games all using the same teleport beam from the lab, which whilst it's a nice looking asset makes the games all look like lazy clones (imho).

I'd quite like to offer a range of teleport beams, etc and give people the choice.

Shall we merge this issue in with the issue at: https://github.com/thestonefox/VRTK/issues/763
as they seem related?

**Comment by dantman** [comment]
I'm mixed on how I feel about adding polish to the rest of the examples. Some polished demos with a variety of environments would be nice to show off the look of VRTK in a full game. But the use of simple shapes in the examples makes it very straightforward and to open an example scene and discover how to use VRTK.

I was just thinking of being able to quickly and straightforwardly demonstrate feature parity with the SteamVR Plugin with an example that works the same.

**Comment by thestonefox** [comment]
Merged with https://github.com/thestonefox/VRTK/issues/763
