### ISSUE TITLE
VRTK_SimplePointer ToggleBeam() bug

### ISSUE THREAD

**Issue by fredwgreene** [thestonefox/VRTK#891]
It seems there is a bug when activating/deactivating the VRTK_SimplePointer via script.
Calling ToggleBeam(false) will not stop displaying the beam unless ToggleBeam(true) has been called twice.
Below is a screenshot of the parameters of the related components.
This project only activates and deactivates via script, not controller input.

Current version: 3.0.1

![simplepointer](https://cloud.githubusercontent.com/assets/25427079/22414327/7ceb4362-e673-11e6-9087-44c53ca4cf33.PNG)

P.S.
Love VRTK and what you've done with it.
Keep up the good work :)

**Comment by thestonefox** [comment]
This is because you have `Hold Button To Activate` unticked. When this is unticked, the pointer toggle works with a click to turn it on, then another click to turn it off.

If you want it to work where you hold a button down to turn it on then releasing the button turns it off then you should tick the `Hold Button To Activate` box.

Internally a state is set on the pointer every time toggle is called. when `Hold Button To Activate` is false, it will toggle that state to 1 on the first `ToggleBeam(true) ` and `ToggleBeam(false)` won't turn it off until that state has been toggled up once more.
