### ISSUE TITLE
[Interactable Objects] Connecting Objects Together

### ISSUE THREAD

**Issue by Codezen** [thestonefox/VRTK#90]
I'm not sure if you are already planning this but:
I would love to see a way of connecting objects together. Things like keys into keyholes, ammo clips and mods on to guns etc.

Once two connectable objects get close enough they would try and orient themselves to connect (locking an axis if needed) and eventually connect when close enough and/or released. 

Thanks for your awesome work on the toolkit!

**Comment by thestonefox** [comment]
I thought I already had an issue with this! Can't find it though :) so thanks for posting it :)

Yeah it's something I want to implement, same as in Job Simulator where you just put an object near something else and it snaps into place.


Now typing that I think I remember where I was talking about it...in the bow mechanics issue!

But yeah, it's something I want to implement

**Comment by djkilgore** [comment]
Are you still planning on implementing this in bow mechanics?
I have a simple modification to the grabbable object script where you provide a string and when the object is picked up all objects with the same tag are also grabbed. You can also supply a Vector3 offset for the grouped object.

Its not very robust but I will submit a pull request if its not being implemented elsewhere

**Comment by thestonefox** [comment]
I'm currently working on the bow mechanics should be ready soon :)

**Comment by thjmorgan** [comment]
I would like to second this request. Specifically, what would be great is if I could grab-and-hold an object (like a key) which has the VR_InteractableObject attached and - with the grabbed object in hand - touch another object (like a door lock) which also has the VR_InteractableObject attached - so I can get notified in "OnTouch" with the grabbed object.

The problem with this currently is that I can't move the objects into one another as both have colliders/collision detection. I could change this in Grabbed/Ungrabbed (detectCollisions=false/true). However, even when doing this, the object passed in StartTouching() seems to be the controller, not the grabbed object.

This makes me feel that the current scripts weren't really made for that use case ;-) --- What do you think of an addition which allows such interactions with grabbed objects? Or, if it can already be done with the current scripts, what do you suggest as the best way?

**Comment by thestonefox** [comment]
@thjmorgan Heh, I was just replying to your other issue before you closed it. I was going to refer to this exact issue, but you've beat me to it :)

Yeah it's something that is a good addition!

**Comment by thestonefox** [comment]
Trello Card https://trello.com/c/NPsRmgYC

**Comment by 10FingerArmy** [comment]
In order to work on a lock, key hole, "insert radio active rods here", plug something into electric sockets and many more we need this to be a general purpose snapping mechanism.

It should be proximity and direction based (e.g. don't snap the key if you are not facing the hole) and then rotate the object into the needed position. Once snapped, it should only allow limited movement, e.g. move along x-axis (min/max) or rotate around z (min/max).

**Comment by asemahassan** [comment]
Following the same issue request: I would also like to add mine here

Hi @thestonefox ,  Is there also a possibility to "snap two objects" based on their relative distance and relative orientation from eachother? Since the objects can be anywhere in the world space. E-g 3D puzzle objects to be docked at right point to complete puzzle.

**Comment by thestonefox** [comment]
Resolved with 
https://github.com/thestonefox/VRTK/pull/670
