### ISSUE TITLE
Support for distinguish long or short press on button/touchpad.

### ISSUE THREAD

**Issue by liamxu** [thestonefox/VRTK#951]
With the usage of touchpad, I'm considering to use a short press to do movement , and use a long press to show the menu. I'm wondering, whether this function could be realized by calculating the duration between the press and release action?
Thanks a lot!

**Comment by bddckr** [comment]
Yeah just subscribe to the respective events on `VRTK_ControllerEvents` and check the time difference.

**Comment by dantman** [comment]
@bddckr There were plans to decouple the current hardcoded controller button mapping values, right? Would it be reasonable to expand that so it's possible – instead of subscribing to controller events from an object – for a script on the controller to make it's own button event for something like "Trackpad longpress -> Menu" and the object select that?

**Comment by bddckr** [comment]
Yeah the idea of "virtual events" could handle that very easily.

**Comment by reznovVR** [comment]
The requested thing can easily be done with the events like bddckr said so is there any reason to keep this open?

Of course this would be a nice event in the core system too but then again there are a lot of buttons and this would probably just clutter the inspectors (button dropdowns) a bit more and add minimal overhead when tracking states and interval. Could be an example script too instead of core stuff.

**Comment by liamxu** [comment]
Thank you for your guys nice replies, such events have been done basing on your suggestion. I will close it.

**Comment by dantman** [comment]
Side note, Coroutines should also help simplify implementing this.

* In the button event handler use `StartCoroutine(MyLongPressCoroutine())` and save the returned coroutine in a variable.
* And start `MyLongPressCoroutine()` with `yield return new WaitForSeconds(longPressDelay);` followed by whatever long-press code you want and end it by setting the saved coroutine variable to null.
* Then in the on-release event for the controller button check if the coroutine is set, if so call `StopCoroutine` on it and set the variable to null.

I suppose actually we could create a helper class that would simplify this for people. A class with a static method `StartLongPress(GameObject gameObject, Action longPressAction, float longPressDelay)` that would return an instance with a `Stop()` method and automatically call whatever long press callback you stick into your code (it would eliminate the need for the user to actually work with any coroutines).
