### ISSUE TITLE
The event UIPointerElementEnter always happen.

### ISSUE THREAD

**Issue by BensonZheng1987** [thestonefox/VRTK#961]
### Environment
 * Source of VRTK ( Github)
 * Version of VRTK  (Github master commit hash a3d898338fef3fc572d960dcbea0840194fb27d5)
 * Version of Unity3D (e.g. Unity 5.5.0f3)

### Steps to reproduce
Example: 034_Controls_InteractingWithUnityUI.unity
Set Activation mode = AlwaysOn of VRTK_UIPointer On the RightController
if you use pointer to touch the ScrollView UI element, The event UIPointerElementEnter always happen.

**Comment by thestonefox** [comment]
This is because when hovering over a ScrollView element it registers the draggable panel element first then it registers the Viewport element and then the ScrollView element, then back to the beginning of the cycle.

Not sure why it is continually finding all 3 elements every time and not just stopping on the first one it finds.

My assumption would be that the unity raycast shouldn't keep casting through unity UI elements.

**Comment by thestonefox** [comment]
A workaround to this is to select the `ScrollView` element and set it to not be a ray target, and then select the `Viewport` element and again set it to not be a ray target.

This means you won't get an `OnEnter` when hovering over the scroll area, but you will get it over the elements within the scroll area still.
