### ISSUE TITLE
Height adjust teleport does not work correctly if terrain Y is not set to 0

### ISSUE THREAD

**Issue by yuqiaoyan** [thestonefox/VRTK#980]
### Environment
 * Source of VRTK (Unity Asset Store)
 * Version of VRTK 3.1.0
 * Version of Unity3D 5.5.1f1

### Steps to reproduce
Go to example scene 10, TerrainTeleporting
Set Terrain Y = 10
Use the bezier pointer to teleport to a different spot on the terrain
Your destination will be set to Y=0 which is below the terrain

### Expected behavior

Whether terrain is set to Y=0 or not zero, I expect to land on the spot that my pointer identifies

### Current behavior

I end up below the terrain

**Comment by thestonefox** [comment]
Ok i know the issue and have a fix. I just need to merge it into master.

The fix is basically. On line 200 of `VRTK_BasicTeleport`

be sure to add the existing Y of the terrain to the height like so:

`position.y = (terrainHeight > position.y ? position.y : Terrain.activeTerrain.GetPosition().y + terrainHeight);`

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/03630c4f0937eecc8f68f592eaf7806c67edd5ce
