### ISSUE TITLE
Switching scenes removes all of the linked objects in the SDK Manager

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#986]
Load up `001_CameraRig_VR_PlayArea` and then switch scenes at runtime by pressing

Trigger + Grip + Touchpad on the right controller

The scene will switch to `002_Controller_Events` but the SDK_Manager has no linked objects.

This is because (I believe) the new SDK Manager force sets things to null and tries to find things in the scene itself. However on scene load these things aren't being found even though they're already pre-set in the script.

@bddckr it affects the following:

* Actual Boundaries
* Actual Headset
* Actual Left Controller
* Actual Right Controller

I'm guessing we shouldn't be setting them to null if one already exists in the parameter.

**Comment by thestonefox** [comment]
Also as a side note. Line 643 of the SDK Manager does a check to see if the `actualLeftController` exists but no check is done for `actualHeadset` or `actualRightController`

I'm guessing this check was hiding a previous error, I would say it should be consistent.

**Comment by bddckr** [comment]
@thestonefox
1. The SDK Manager is set up by default to auto-populate the object references now. The example scenes weren't updated to use SteamVR and default to the Fallback SDK instead. The thought was "force the user to specify his SDK because we support many SDKs now".
So to fix your use case: Load every scene, click on the SDK manager and set it to SteamVR via the quick select button. Save the scene.

There is no forcing to null. It's just that the manager isn't set up the way you want it to be to allow for the scene switching. I leave the decision to reverse my idea of forcing the user to specify the used SDK instead of defaulting to SteamVR (which may not be installed and therefore throw errors when loading the example scenes) to you 😛.

2. That change wasn't introduced by me, it was introduced by the Daydream PR. I think it was done because Daydream only supports one controller which the VRTK Daydream SDK assigns as the right controller instead of the left one, so the left one is null all the time in that case.
I don't think we should handle a null right controller because that would hide issues.

**Comment by Rahulxx01** [comment]
How to save position of the player when switching the scenes and when I return to that previous scene it should return to the same position back???
